### ISSUE TITLE
How can I flatten a nested reference?

### ISSUE THREAD

**Issue by DavidGrinberg** [kotlin-orm/ktorm#107]
Lets say we have the normal Department entity, but we want the Employee entity to only show the department name, not the fully department object, e.g.:

```
interface Employee : Entity<Employee> {
    val id: Int?
    var name: String
   ...
    var departmentName: String
}
```

How would we define our bindings to accommodate this _without_ storing the department name on the employee table? 

```
object Employees : Table<Employee>("t_employee") {
    val id by int("id").primaryKey().bindTo { it.id }
    val name by varchar("name").bindTo { it.name }
   ...
    val departmentId by int("department_id").references(Departments) { /* somehow map this to deptName*/ }
}
```

**Comment by vincentlauvlwj** [comment]
Is there any problem to have a full department object in `Employee`? I think it's fine.

**Comment by DavidGrinberg** [comment]
If I'm trying to serialize the object to what the API wants to return I'd prefer to have it more normalized for a friendlier looking API. I don't want API domain objects to be so coupled to my table setup.

**Comment by ashokgelal** [comment]
I've run into this problem myself - returning a "cleaner" object based on what the API wants. The only way I could solve it is by creating a "wrapper data class" for an entity and returning that instead (sometimes just a map works). I defined a `asResource()` method on the entity and map the results to this method. It is not elegant but works.

**Comment by vincentlauvlwj** [comment]
In this case, I'd prefer creating a DTO class and return that instead, which is a general way as far as I know: 

```kotlin
interface Employee : Entity<Employee> {
    val id: Int
    val name: String
    val department: Department

    fun toEmployeeDTO() = EmployeeDTO(
        id = id,
        name = name,
        departmentName = department.name
    )
}

data class EmployeeDTO(
    val id: Int,
    val name: String,
    val departmentName: String
)
```

**Comment by DavidGrinberg** [comment]
Perhaps a better way of viewing this is via inheritance. Let's say we have a `person` table, and and the `employee` table that keys off `person.id`. I'd like to have an entity object for `employee` that has the parent `person` object flattened into it. It seems like ktorm doesn't support this for now

**Comment by vincentlauvlwj** [comment]
Then this is much like another issue, polymorphic relationships (#78)

**Comment by raderio** [comment]
@vincentlauvlwj in your case it will extract the entire `Department` object with all the fields, which is not need for some use cases.

@DavidGrinberg maybe for this use case there should be multiple entities mapped to same table? One with all the fields and one just with required fields.

**Comment by raderio** [comment]
Also this will be solved by https://github.com/vincentlauvlwj/Ktorm/issues/100
