### ISSUE TITLE
CachedRowSet::getTimestamp drops fractional seconds > 3

### ISSUE THREAD

**Issue by ragnese** [kotlin-orm/ktorm#130]
In other words, getTimestamp only has millisecond precision, but MySQL, at least, supports up to microseconds. 

java.sql.Timestamp supports nanos, and the official mysql connector/j jdbc driver also supports microseconds. So CachedRowSet::getTimestamp drops some precision.

**Comment by vincentlauvlwj** [comment]
Thank you, will fix in next version.

**Comment by efenderbosch** [comment]
Did a little bit of research on this. The various implementations support different fractional second precision. I'm not sure if this warrants inclusion in SqlDialect, or treating all as supporting nanos (9 digits) is sufficient.

MySQL - 6 digit precision
PostgreSQL - 6 digit precision
MS SQL Servier - 7 digit precision
Oracle - 9 digit precision
SQLite - 3 digit precision if stored at Text (ISO-8601)

**Comment by vincentlauvlwj** [comment]
Fixed in Ktorm 3.1.0.
