### ISSUE TITLE
Allow offset without limit

### ISSUE THREAD

**Issue by arustleund** [kotlin-orm/ktorm#147]
Some dialects, such as PostgreSQL, allow the user to specify an offset without specifying a limit, however, the API currently forces the user to specify both. A simple change could be to change the signature to take nullable values, as it appears the SQLFormatter is already checking for nulls.

**Comment by vincentlauvlwj** [comment]
Great!

**Comment by vincentlauvlwj** [comment]
Implemented in 3.3.0
