### ISSUE TITLE
SQL Server: Support explicit table schema prefix in queries

### ISSUE THREAD

**Issue by robvari** [kotlin-orm/ktorm#154]
Hi. 

We have an issue when using Ktorm with SQL Server. The queries do not work with a db user which has no default schema, since the schema defined in the connection (e.g. via spring data source) is ignored / not supported by the SQL server driver. 

It would be good to be able to enforce a schema prefix in the queries / pass a schema in the entity definition.

E.g.

```
object DimDate : Table<Nothing>("DimDate", "MySchema") { ... }

=> 

SELECT * FROM MySchema.DimDate
```

It seems this is not possible right now. Is there a suggested work around?

**Comment by vincentlauvlwj** [comment]
The same issue as https://github.com/vincentlauvlwj/Ktorm/issues/89

**Comment by robvari** [comment]
Thanks for checking my ticket. Yes, it is the same root issue. It is a bit more annoying for SQL Server since the work around via connection URL is not working. Its not supported by SQL Server.

See e.g. https://docs.microsoft.com/en-us/sql/connect/jdbc/jdbc-4-1-compliance-for-the-jdbc-driver?view=sql-server-ver15

**Comment by hangingman** [comment]
@vincentlauvlwj 
Currently, this schema issues are opened by name of SQL Server(#154) and PostgreSQL(#89).
But I want this feature for MySQL also.
So, I think it may be core feature if there is no problem.

**Comment by vincentlauvlwj** [comment]
@hangingman Yes, will be a core feature.

**Comment by vincentlauvlwj** [comment]
Supported in Ktorm 3.1.0
