### ISSUE TITLE
singleOrNull 方法 相同数据有多条时 返回null的问题, 只存在单条数据时没有问题

### ISSUE THREAD

**Issue by hyxj1220** [kotlin-orm/ktorm#167]
CREATE TABLE node
(
    id bigserial ,
    title character varying COLLATE pg_catalog."default" NOT NULL
)

INSERT INTO node(title) VALUES ('hello');
INSERT INTO node(title) VALUES ('hello');

println(database.sequenceOf(Nodes).singleOrNull { it.title eq "hello" })  

以上测试代码当hello 存在大于1条时  会输出null

**Comment by vincentlauvlwj** [comment]
看看文档，里面是不是有一句话 null if the sequence is empty or has more than one element.

https://ktorm.liuwj.me/api-docs/me.liuwj.ktorm.entity/single-or-null.html

如果你想在有多条数据的时候返回第一条，用 `firstOrNull`
