### ISSUE TITLE
求问如何支持子查询

### ISSUE THREAD

**Issue by gsy13213009** [kotlin-orm/ktorm#168]
- left join 表里有多条记录，只取一条记录

```sql
select a.id from app a
left join (select uid,id,name from weixin where 索引条件 group by uid) b on a.id=b.uid
```
- [参考资料](https://blog.csdn.net/niuzaiwenjie/article/details/97240943?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.edu_weight&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.edu_weight)

**Comment by vincentlauvlwj** [comment]
> select uid,id,name from weixin where 索引条件 group by uid

首先这条 SQL 是有语法错误的，SQL 语法规定，在使用 group by 时，select 子句中出现的字段，要么是 group by 中的列，要么被包含在聚合函数中，即使有的数据库引擎不会报错，但是执行的结果也是未定义行为，所以写出这样一条 SQL，没人能理解你想干什么

**Comment by vincentlauvlwj** [comment]
然后 Ktorm 确实不支持子查询，因为这个在业务代码中几乎不会用到，你能想到的大部分 case，都能通过拆分或者改写的方式，使用简单的单表查询就可以实现，没有必要使用这种复杂的方式。比如阿里巴巴的编码规范，就禁止在业务代码中使用子查询。

当然你确实要用也可以，Ktorm 也支持原生 SQL...

**Comment by gsy13213009** [comment]
感谢大佬解答🙈，主要是不是很熟，查了关于`left join 表里有多条记录，只取一条记录`的好多资料，都是用的子查询😂
