### ISSUE TITLE
redisson 读取表实体时，提示ClassCastException

### ISSUE THREAD

**Issue by MarkJane** [kotlin-orm/ktorm#171]
![image](https://user-images.githubusercontent.com/3880402/87744189-64dc7e00-c81d-11ea-85ff-a4e014bd65ed.png)

java.lang.ClassCastException: class com.sun.proxy.$Proxy7 cannot be cast to class com.variflight.dao.EUser (com.sun.proxy.$Proxy7 is in unnamed module of loader 'bootstrap'; com.variflight.dao.EUser is in unnamed module of loader 'app')

**Comment by vincentlauvlwj** [comment]
这个与你使用的序列化方式有关，可以发一下你的 redisson 的相关配置代码吗

**Comment by MarkJane** [comment]
没有指定，使用的默认的 codec=org.redisson.codec.FstCodec

**Comment by MarkJane** [comment]
java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME:com.sun.proxy.$Proxy10 loader:jdk.internal.loader.ClassLoaders$AppClassLoader@3fee733d

取出的时候 redission proxy 编号10， 但是我看 redis里 存的 是  proxy11,  这个原因导致的？

**Comment by MarkJane** [comment]
> 这个与你使用的序列化方式有关，可以发一下你的 redisson 的相关配置代码吗

大佬有空帮看下上面2条，  这个是不是和 Entity 里的 proxy代理有关系？

**Comment by MarkJane** [comment]
![image](https://user-images.githubusercontent.com/3880402/87750741-d8d35200-c82e-11ea-9f70-0b602ad64f5e.png)

![image](https://user-images.githubusercontent.com/3880402/87750800-04eed300-c82f-11ea-9422-8775450d8f3f.png)

**Comment by MarkJane** [comment]
![image](https://user-images.githubusercontent.com/3880402/87750843-1d5eed80-c82f-11ea-99df-1c8dbece5fb5.png)

**Comment by MarkJane** [comment]
> 这个与你使用的序列化方式有关，可以发一下你的 redisson 的相关配置代码吗

刚尝试 改成 SerializationCodec 就ok了， 其他序列化方式均不行

**Comment by vincentlauvlwj** [comment]
可以看看文档 https://ktorm.liuwj.me/zh-cn/entities-and-column-binding.html#%E5%BA%8F%E5%88%97%E5%8C%96

Ktorm 目前只支持两种序列化方式：

- 默认的 JDK 序列化，无需额外配置，默认支持
- Jackson 序列化，需要引入 ktorm-jackson 模块，往 `ObjectMapper` 中注册一个 `KtormModule`
