### ISSUE TITLE
实体类更新API是否可以提供一个更新全部列的方法

### ISSUE THREAD

**Issue by superwy** [kotlin-orm/ktorm#174]
目前有一个flushChanges方法，但是需要更新变量后才会更新相关的字段。
有没有一个方法可以强制更新全部的字段，不受字段更新影响

**Comment by vincentlauvlwj** [comment]
使用场景是什么，其他字段没有变化为什么要更新

**Comment by superwy** [comment]
因为有时候需要更新数据实体类的大部分字段， 而且数据实体类是从领域对象转化的，  这个时候不需要再去查一次数据实体类。

**Comment by vincentlauvlwj** [comment]
那直接用 DSL 的 `update` 方法就好了，想更新哪些字段都可以：

```kotlin
database.update(Employees) {
    it.name to name
    it.salary to salary
    where {
        it.id eq id
    }
}
```

**Comment by superwy** [comment]
那么实体类API， 是否可以提供一个更新全部字段的API呢？

**Comment by vincentlauvlwj** [comment]
下个版本吧

**Comment by vincentlauvlwj** [comment]
Ktorm 3.1.0 增加了一个实体对象的 `update` 函数，用法看这里 https://github.com/kotlin-orm/ktorm/releases/tag/v3.1.0
