### ISSUE TITLE
Batch delete?

### ISSUE THREAD

**Issue by ragnese** [kotlin-orm/ktorm#176]
As far as I know, JDBC allows batching of DELETE statements. Can we get a batchDelete in ktorm alongside batchInsert and batchUpdate?

**Comment by vincentlauvlwj** [comment]
I don't think it's necessary. We already have a `delete` function: 

```kotlin
database.delete(Employees) { condition }
```

**Comment by ragnese** [comment]
Yeah, I think that's fair. I had a specific case where it might've been a little more convenient, but it was easy enough to just do exactly as you suggested.
