### ISSUE TITLE
Generated SQL code has quotes when using schema.table format

### ISSUE THREAD

**Issue by tromper** [kotlin-orm/ktorm#183]
I'm trying to use ktorm to access some views on a SQL Server database.  The views are under a schema.  With exposed, I just made the table names in the format schema.tablename and the generated SQL code worked fine.  With ktorm, I am getting generated SQL code where the schema.table name is getting double quoted, and I get an invalid object name back from jdbc.  For example, if I have "test.gender" as the table name in the object, ktorm generates

SELECT * FROM "test.gender" (DOESN'T WORK)

If I use the same db connection, but the Native SQL approach without the double quotes to debug,it works fine

SELECT * FROM test.gender  (WORKS)

I really prefer the simplicity and syntax of ktorm compared to Exposed, but I haven't been able to get very far :(

**Comment by vincentlauvlwj** [comment]
The same issue as #89, #154

**Comment by vincentlauvlwj** [comment]
I'm sorry for the inconvenience. Ktorm will support schema in version 3.1, which will be release by the end of this month.

**Comment by tromper** [comment]
Understood, thanks for the quick reply.

-S-

**Comment by vincentlauvlwj** [comment]
Ktorm 3.1.0 released, support schema & catalog.
