### ISSUE TITLE
Entity不支持Jackson的@JsonFormat注解吗？

### ISSUE THREAD

**Issue by mealayaria** [kotlin-orm/ktorm#186]
在Entitiy里对LocalDateTime使用了
`@get:JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")`

在使用的时候会直接报错
`Caused by: java.time.format.DateTimeParseException: Text '2020-07-06 11:16:48' could not be parsed at index 10
`

同样的代码如果放在data class里解析正常，翻了一下文档只提到支持简单的Jackson注解，我不太清楚@JsonFormat是不是简单的Jackson注解，所以我的疑问是，Entity是不是不支持@JsonFormat注解？还是我某些地方使用错误？

另外，文档中ktorm-jackson支持简单注解，那么哪些注解不被支持，我很疑惑，希望能在文档中明确一下。

**Comment by vincentlauvlwj** [comment]
目前支持的注解只有三个：

- `JsonIgnore`
- `JsonProperty`
- `JsonAlias`

其他的都不支持

**Comment by mealayaria** [comment]
好的，感谢解答。
