### ISSUE TITLE
entity的model是interface我如何手动用代码创建一个

### ISSUE THREAD

**Issue by yuzd** [kotlin-orm/ktorm#189]
我该如何自己用代码创建一个这个model？

```kotlin
interface Department : Entity<Department> {
    companion object : Entity.Factory<Department>()
    val id: Int
    var name: String
    var location: String
}
```

**Comment by vincentlauvlwj** [comment]
这样：

```kotlin
val department = Department()
```

或者这样：

```kotlin
val department = Entity.create<Department>()
```

**Comment by yuzd** [comment]
第二种是对的
第一种方式提示不对 因为是interface 没有构造方法

然后我发现我生成的model里面 都是val修饰的字段。还好你提供了一个 model["xxxx"] = yyy 的方式

**Comment by vincentlauvlwj** [comment]
1. 第一种也是对的 https://ktorm.liuwj.me/zh-cn/entities-and-column-binding.html
2. 需要修改的话，把字段定义成 var，最好不要用 model["xxxx"] = yyy 的方式改，类型不安全

**Comment by yuzd** [comment]
懂了 我没有配置 companion object : Entity.Factory<Department>() 导致的 
多谢
