### ISSUE TITLE
Does it support Kotlin Native ?

### ISSUE THREAD

**Issue by Taymindis** [kotlin-orm/ktorm#191]
I am currently looking for ORM for kotlin native, I'm wondering is this the one?

**Comment by vincentlauvlwj** [comment]
I'm sorry to say no. Ktorm is implemented based on JDBC. It can not run on Kotlin native.

**Comment by emilesteenkamp-underpaid** [comment]
@vincentlauvlwj I don't understand why being based off of JDBC imposes the limitation that Ktorm can not run on Kotlin Native. Can you add more detail on why?
