### ISSUE TITLE
使用data class进行列绑定, 如何关联其他对象?

### ISSUE THREAD

**Issue by dawsonlee1790** [kotlin-orm/ktorm#193]
使用interface进行列绑定的时候, 可以使用references关联其他对象, 但是使用data class进行列绑定时, 在doCreateEntity方法中, 如何绑定呢?

**Comment by vincentlauvlwj** [comment]
文档说了不支持 https://ktorm.liuwj.me/zh-cn/define-entities-as-any-kind-of-classes.html#%E7%9B%B8%E5%85%B3%E9%99%90%E5%88%B6

**Comment by dawsonlee1790** [comment]
不好意思, 之前没读懂, 以为存在其他关联方式, 只是不能使用references这种方式进行对象关联
