### ISSUE TITLE
请问对PostgreSQL的 string_to_array(stationIds, ",") @> ARRAY[1,2]  如何操作？

### ISSUE THREAD

**Issue by MarkJane** [kotlin-orm/ktorm#195]
```kotlin
data class SplitContainsExpression(
        val type: String,
        val left: ScalarExpression<*>,
        val right: ScalarExpression<*>,
        override val sqlType: SqlType<Boolean>,
        override val isLeafNode: Boolean = false,
        override val extraProperties: Map<String, Any> = emptyMap()
    ) : ScalarExpression<Boolean>()

 fun <T: Any> ColumnDeclaring<T>.splitContains(value: Array<String?>, separator: String = ","): SplitContainsExpression {
        return SplitContainsExpression("@>", FunctionExpression(
            functionName = "string_to_array",
            arguments = listOf(
                asExpression(),
                ArgumentExpression(separator, VarcharSqlType)
            ),
            sqlType = TextArraySqlType
        ), ArgumentExpression(value, TextArraySqlType), BooleanSqlType)
    }
```
`
 val result = DB.sequenceOf(TUser).filter{
            it.stationIds.splitContains(arrayOf("12"))
        }.toMutableList()
        println(result)`

运行之后提示：
![image](https://user-images.githubusercontent.com/3880402/95731272-e3787880-0cb1-11eb-9cfc-eb51125685d9.png)

请教上面的实现是不是有问题？ 应该在哪里添加 expression type?

**Comment by vincentlauvlwj** [comment]
参考一下自定义运算符的文档：https://www.ktorm.org/zh-cn/operators.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BF%90%E7%AE%97%E7%AC%A6

你还差最后一个步骤，创建一个 `PostgreSqlFormatter` 的子类，在里面检查你的 `SplitContainsExpression` 表达式，生成正确的 SQL，然后把这个 sql formatter 通过方言的方式注册到 `Database` 里面

这里有个详细的教程，可以看看 https://skyblond.info/archives/751.html

**Comment by MarkJane** [comment]
大佬，能直接在 PostgreSqlFormatter里 覆盖扩展 visitUnknown 方法吗，而不需要单独自定义MyCustomSqlFormatter 以及 MyPostgresqlDialect 类

**Comment by vincentlauvlwj** [comment]
但是 `PostgreSqlFormatter` 是 Ktorm 里面的代码，不在你的项目里面，你要怎么修改呢？

**Comment by MarkJane** [comment]
能将PostgreSqlFormatter 抽出一个扩展类， 我们直接扩展这个指定扩展类的visitUnkown方法， 然后在PostgreSqlFormatter 的VisitUnkown 方法中调用 扩展类的visitUnkown方法的结果吗？

**Comment by vincentlauvlwj** [comment]
现在不就是这样子吗

**Comment by MarkJane** [comment]
```kotlin
open class MyPostgreSqlDialect : SqlDialect {
    override fun createSqlFormatter(database: Database, beautifySql: Boolean, indentSize: Int): SqlFormatter {
        return MyPostgreSqlFormatter(database, beautifySql, indentSize)
    }
}

open class MyPostgreSqlFormatter(database: Database, beautifySql: Boolean, indentSize: Int) : PostgreSqlFormatter(database, beautifySql, indentSize) {

    override fun visitUnknown(expr: SqlExpression): SqlExpression {
        return if (expr is SplitContainsExpression) {
            visit(expr.left)
            writeKeyword("${expr.type} ")
            visit(expr.right)
            expr
        } else {
            super.visitUnknown(expr)
        }
    }
}

data class SplitContainsExpression(
    val type: String,
    val left: ScalarExpression<*>,
    val right: ScalarExpression<*>,
    override val sqlType: SqlType<Boolean>,
    override val isLeafNode: Boolean = false,
    override val extraProperties: Map<String, Any> = emptyMap()
) : ScalarExpression<Boolean>()

fun ColumnDeclaring<String>.string2Array(separator: String = ",") = FunctionExpression(
    functionName = "string_to_array",
    arguments = listOf(
        asExpression(),
        ArgumentExpression(separator, VarcharSqlType)
    ),
    sqlType = TextArraySqlType
)

fun ColumnDeclaring<String>.splitContains(value: Array<String?>, separator: String = ","): SplitContainsExpression {
    return SplitContainsExpression("@>", string2Array(separator), ArgumentExpression(value, TextArraySqlType), BooleanSqlType)
}
```
运行结果：
`val result = DB.sequenceOf(TUser).filter{
            it.stationIds.splitContains(arrayOf("12"))
        }.toMutableList()
        println(result)`
能生成正常的sql ，下图的报错提示 是 TextArraySqlType 使用错误吗？

![image](https://user-images.githubusercontent.com/3880402/95810328-4534f300-0d43-11eb-90f1-37e5a9a2a3e0.png)

抱歉表达的不够清晰， 现在是需要定义一个继承PostgreSqlFormatter的类来扩展，能不能直接类似于PostgreSqlFormatterExtend.Companion.customVisitUnkown 方法， PostgreSqlFormatter 的visitUnkown方法 直接调 customVisitUnkown 的结果，这样就不需要定义 MyCustomSqlFormatter 以及 MyPostgresqlDialect 类

**Comment by vincentlauvlwj** [comment]
这应该是你生成的 SQL 有问题，你再检查一下，可以把 SQL 复制到 postgresql 的控制台跑一跑试试

**Comment by vincentlauvlwj** [comment]
搞个微信群的话，我个人也不怎么会运营，一天到晚冷冷清清就太尴尬了，所以有问题还是直接在 issue 里面提吧，我会尽量解答的
