### ISSUE TITLE
Postgres notification handler

### ISSUE THREAD

**Issue by asad-awadia** [kotlin-orm/ktorm#196]
What is the best way to attach a notification listener with Postgres using Ktorm?

**Comment by asad-awadia** [comment]
@vincentlauvlwj

**Comment by vincentlauvlwj** [comment]
What do you mean by notification listner?

**Comment by asad-awadia** [comment]
To receive notifications from postgres triggers and listen/notify.


https://tapoueh.org/blog/2018/07/postgresql-listen-notify/

**Comment by asad-awadia** [comment]
@vincentlauvlwj any thoughts?

**Comment by vincentlauvlwj** [comment]
1. I don't think an ORM framework should implement this. Maybe you should use a PostgreSQL client directly. 
2. Ktorm is implemented based on JDBC, but as far as I know, PostgreSQL's JDBC client doesn't support listen & notify, so...

**Comment by asad-awadia** [comment]
Okay np
