### ISSUE TITLE
update 或者 insert 或者 delete 的有没有这样的扩展

### ISSUE THREAD

**Issue by yuzd** [kotlin-orm/ktorm#201]
```kotlin

val Database.departments get() = this.sequenceOf(Departments)
val Database.employees get() = this.sequenceOf(Employees)
```
以上的扩展很方便的可以直接用 db.departments.xxxxxx  来查询

对于update 或者 insert 或者 delete 的有没有这样的扩展

比如目前我这么用的
db.update(Departments){
set(xx,yy)
where{

}
} 

我希望这么用
db.departments.update{
set(xx,yy)
where {
}
}

**Comment by vincentlauvlwj** [comment]
你找找是不是本来就有 `database.departments.add()` 和 `database.departments.update()` 这两个函数

**Comment by yuzd** [comment]
update 我看是传一个 entity 的 
我这么用会提示出错
db.departments.update{
set(xx,yy)
where {
}
}

**Comment by vincentlauvlwj** [comment]
你想要的话可以写一个这样的扩展函数：

```kotlin
fun <E : Entity<E>, T : Table<E>> EntitySequence<E, T>.update(block: UpdateStatementBuilder.(T) -> Unit): Int {
    return this.database.update(this.sourceTable, block)
}
```

但是说实话，`database.departments` 这种扩展是给实体对象用的，把 DSL 混在里面有点不伦不类

**Comment by yuzd** [comment]
谢谢

是这样的 我用代码生成器生成每个table
```kotlin
object AccountDao : Table<Account>("accounts"){}
interface Account : Entity<Account> {}

```

还会生成一个汇总的Tables
```kotlin
object Tables {
val account = AccountDao
val Database.accounts get() = this.sequenceOf(AccountDao)
}

```
我在写代码的时候可以直接用
db 的扩展 

这样对我就比较方便了
