### ISSUE TITLE
doCreateEntity option to return null

### ISSUE THREAD

**Issue by P1NG2WIN** [kotlin-orm/ktorm#205]
How can i do smth like this?

```
object ColorsTable: BaseTable<ProductColor>("colors") {
    val code = int("code").primaryKey()
    val name = varchar("name")
    val firstHex = varchar("first_hex")
    val secondHex = varchar("second_hex")

    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean): ProductColor? {
        return ProductColor(
            code = row[code] ?: return null,
            name = row[name] ?: return null,
            firstHex = row[firstHex] ?: return null,
            secondHex = row[secondHex] ?: return null
        )
    }
}
```

**Comment by vincentlauvlwj** [comment]
Why not return an empty object instead of null?

**Comment by P1NG2WIN** [comment]
Why do I need a color on the client without a name, a hex code. Or a user without id, name, email and so on.

With option to return null i can do mapNotNull { ColorsTable.doCreateEntity(row) }

**Comment by vincentlauvlwj** [comment]
But this can be implemented by `ColorsTable.createEntity(row).takeIf { it.code == null || it.name == null }`

**Comment by P1NG2WIN** [comment]
> But this can be implemented by `ColorsTable.createEntity(row).takeIf { it.code == null || it.name == null }`

 Hmm, this is not so beauty I think but okay, will use your variant
