### ISSUE TITLE
Postgres Async Kotlin/Native

### ISSUE THREAD

**Issue by caffeine-mgn** [kotlin-orm/ktorm#211]
Hello! Can you add support Kotlin Common?

Very soon I will make release 0.1.26 [Binom](https://github.com/caffeine-mgn/pw.binom.io/tree/feature/0.1.26) Library. It contains [PostgreSQL Connector](https://github.com/caffeine-mgn/pw.binom.io/tree/feature/0.1.26/db/postgresql-async) for Kotlin Common (jvm/native). Also, later I can add async connector for MySQL

**Comment by vincentlauvlwj** [comment]
We will support asynchronous and coroutines on top of [R2DBC](http://r2dbc.io/), but currently no plan to support Kotlin/Native yet.
