### ISSUE TITLE
filterColumns如何去除联表里面的字段

### ISSUE THREAD

**Issue by yamijia1** [kotlin-orm/ktorm#222]
filterColumns { it.columns - it字段 A. }这样是没问题 但如果这个表里面有一个值是用references关联到其他表的应该如何去做,
在代码里面加上filterColumns 查询出来的数据就只有references相关联的表的 id 其余的字段都没有返回
select()同理 ,文档上withReferences值为true的时候会自动创建references相关联的表的实体对象 但是我不管是设置成 true 还是 false 相关联的对象只有 id 这一个字段 只有加上joinReferencesAndSelect才能正常显示 但是joinReferencesAndSelect也不能做筛选

**Comment by vincentlauvlwj** [comment]
假设 `Departments.location` 就是你不要的字段，可以这样写：

```kotlin
val query = database
    .from(Employees)
    .leftJoin(Departments, on = Employees.departmentId eq Departments.id)
    .select(Employees.columns + Departments.columns - Departments.location)
```
