### ISSUE TITLE
insert 改成用 set 方式后 没有类型检查吗？

### ISSUE THREAD

**Issue by yuzd** [kotlin-orm/ktorm#223]
![image](https://user-images.githubusercontent.com/16083659/102714003-fdb08180-4306-11eb-8e1d-c0a1487212b2.png)

IsActive 是 bool 类型的。
但是也没有提示错误

**Comment by vincentlauvlwj** [comment]
这个是故意为之，`to` 函数也是这样的，你运行就知道了，这个地方的类型检查放到了运行时

**Comment by vincentlauvlwj** [comment]
在之前版本的 Kotlin 里面，类型推断还不是很完善，`set` 函数传入 null 时，比如 `set(it.name, null)`，`it.name` 会被推断为 `Column<*>`，没有办法匹配到这个函数签名上 `fun <C : Any> set(column: Column<C>, value: C?)`，所以只能给 `set` 函数增加一个无泛型的重载版本 `fun set(column: Column<*>, value: Any?)`

后来 Kotlin 1.4 改进了类型推断算法， 解决了这个问题，但是为了保持兼容，这个函数还是保留了下来

**Comment by yuzd** [comment]
这个不完美呀
