### ISSUE TITLE
请教下有什么办法可以 开启了 Spring 支持之后，useTransaction 还能使用

### ISSUE THREAD

**Issue by yuzd** [kotlin-orm/ktorm#224]
注意：开启了 Spring 支持之后，useTransaction 方法将不能使用，请改用 Spring 框架提供的 @Transactional 注解，否则会抛出异常：java.lang.UnsupportedOperationException: Transaction is managed by Spring, please use Spring’s @Transactional annotation instead.

主要是开发的时候想避免因为@Transactional注解的一些坑

**Comment by vincentlauvlwj** [comment]
暂时不支持，要么用 `Database.connectWithSpringSupport`，完全使用 Spring 事务，要么用 `Database.connect`，统一使用 `useTransaction`
