### ISSUE TITLE
update 中 decimal 无法使用 表达式运算

### ISSUE THREAD

**Issue by HanaForward** [kotlin-orm/ktorm#229]
database.update(Employees) {
    set(it.salary, it.salary + 100)
    where { 
        it.id eq 1 
    }
}
对于decimal类型的字段是否仍然有效?
如果 it.salary 的描述是    decimal("salary").bindTo { it.salary }
继续使用当前示例则无法通过编译检查

**Comment by vincentlauvlwj** [comment]
类型不匹配，应该这样：

```kotlin
set(it.salary, it.salary + 100.toBigDecimal())
```

**Comment by HanaForward** [comment]
database.update(Employees) {
set(it.salary, it.salary + 100.toBigDecimal())
where {
it.id eq 1
}
}


 None of the following candidates is applicable because of receiver type mismatch: 
public inline operator fun BigDecimal.plus(other: BigDecimal): BigDecimal defined in kotlin
public inline operator fun BigInteger.plus(other: BigInteger): BigInteger defined in kotlin

**Comment by vincentlauvlwj** [comment]
需要 import 

```kotlin
import org.ktorm.dsl.plus
```
