### ISSUE TITLE
Allow setting default transaction isolation level on TransactionManager implementations

### ISSUE THREAD

**Issue by ragnese** [kotlin-orm/ktorm#231]
It would be helpful to allow setting `defaultIsolation` on JdbcTransactionManager and SpringManagedTransactionManager, etc.

It may be surprising to always default it to REPEATABLE_READ. Some DataSource impls already have an option to set the default isolation level. Likewise, the database itself also has a default isolation level that can be adjusted. It seems reasonable to either allow the caller to set it, or to at least use the DataSource or Connection passed in to set the default.

Also, Database.connect should be updated to allow passing in a default isolation level if the TransactionManager will take it as a constructor argument. If it just uses the datasource/connection, then the API doesn't need to change, but it should probably be documented.

Thank You!

**Comment by vincentlauvlwj** [comment]
Agree!! I've thought about this for a long time. Always using `REPEATABLE_READ` is indeed not a good practice. 

I will make the `isolation` param nullable to allow using the default isolation level of the underlying datasource. This will be done in version 3.3.0

**Comment by vincentlauvlwj** [comment]
Fixed in version 3.3.0.
