### ISSUE TITLE
Fixtures and ktorm

### ISSUE THREAD

**Issue by sean-abbott** [kotlin-orm/ktorm#232]
This is really a question not an issue. 

I was wondering if anyone knew of anywhere where people were using fixtures and a fixture library like https://github.com/appmattus/kotlinfixture with ktorm. I'm fairly new to kotlin and I'm struggling a bit with figuring out how to do this. The libraries auto setup fails with reflection issues if you try to pass it just the interface, so I thought maybe i'd make a fixture class that implements the interface in order to generate tests but so far haven't gotten that working either. 

I was just wondering if you folks who were writing this had any experience with anything like this.

Thank you!

**Comment by vincentlauvlwj** [comment]
Maybe you should raise an issue to the `kotlinfixture` project to ask them how to support interfaces.
