### ISSUE TITLE
Possible bug in Insert or Update

### ISSUE THREAD

**Issue by PedroD** [kotlin-orm/ktorm#234]
Hello @vincentlauvlwj !

In the PostgreSqlTest.kt file you find the following test:

```kotlin
    @Test
    fun testBulkInsertOrUpdate() {
        database.bulkInsertOrUpdate(Employees) {
            item {
                set(it.id, 1)
                set(it.name, "vince")
                set(it.job, "trainee")
                set(it.salary, 1000)
                set(it.hireDate, LocalDate.now())
                set(it.departmentId, 2)
            }
            item {
                set(it.id, 5)
                set(it.name, "vince")
                set(it.job, "engineer")
                set(it.salary, 1000)
                set(it.hireDate, LocalDate.now())
                set(it.departmentId, 2)
            }
            onConflict(it.id) {
                set(it.job, it.job)
                set(it.departmentId, excluded(it.departmentId))
                set(it.salary, it.salary + 1000)
            }
        }

        database.employees.find { it.id eq 1 }!!.let {
            assert(it.job == "engineer") // <---------------- Notice that this here should be "trainee"
            assert(it.department.id == 2)
            assert(it.salary == 1100L) // <--------- Why 1100?!
        }

        database.employees.find { it.id eq 5 }!!.let {
            assert(it.job == "engineer")
            assert(it.department.id == 2)
            assert(it.salary == 1000L) // <--------- Why 1000?!
        }
    }
```

This test is passing but maybe it should fail, because employee with id = 1 is a trainee? Why did it change to engineer?

In other words, what is the difference between:

```kotlin
set(it.salary, it.salary + 1000)
```

and

```kotlin
set(it.salary, excluded(it.salary) + 1000)
```

?

Thanks!

**Comment by vincentlauvlwj** [comment]
Our tests are running based on some prepared data, check here: 

https://github.com/kotlin-orm/ktorm/blob/master/ktorm-support-postgresql/src/test/resources/init-postgresql-data.sql#L35-L43

and here: 

https://github.com/kotlin-orm/ktorm/blob/master/ktorm-support-postgresql/src/test/kotlin/org/ktorm/support/postgresql/PostgreSqlTest.kt#L39-L53

The `init` function will execute before each test functions, and the `destroy` function will execute after them finished.

**Comment by vincentlauvlwj** [comment]
`set(it.salary, it.salary + 1000)` will generate SQL `salary = t_employee.salary + 1000`.

`set(it.salary, excluded(it.salary) + 1000)` will generate `salary = EXCLUDED.salary + 1000`.

 The special excluded table is used to reference values originally proposed for insertion, see the document https://www.postgresql.org/docs/9.5/sql-insert.html

**Comment by PedroD** [comment]
What confuses me is what t_employee.salary really is. It seems to take the value of the last row we are inserting during a batch update?

To me both the excluded and the t_employee.salary would generate the same outcome. What am I missing?
