### ISSUE TITLE
Allow pre-insert and pre-updated event listeners

### ISSUE THREAD

**Issue by JGulbronson** [kotlin-orm/ktorm#241]
Hi Vincent, first off I wanted to say I'm really enjoying the library so far! I've been playing around with it for a couple days, and it's very refreshing coming from Hibernate.

I'm opening this "issue" to suggest a new feature, pre-insert/update event listeners. Something like
```kotlin
interface PreInsertListener {
    /**
     * Returns true if the entity should be inserted in to the database, otherwise false.
     * This method offers an opportunity to modify an entity before it is written to the database.
     */
    fun onPreInsert(entity: Entity<*>) : Boolean
}
```

This is particularly useful for cases where you might want to update timestamps in the code, rather than rely on the database, to make testing easier. That is, you could have an implementation like:
```kotlin
class TimestampedEntityPreInsertListener(
    private val clock: Clock
) : PreInsertListener {
    override fun onPreInsert(entity: Entity<*>): Boolean {
        if (entity is DbTimestampedEntity) {
            entity.createdAt = clock.instant()
            entity.updatedAt = clock.instant()
        }
        return true
    }
}
```

And then you could have different implementations of `Clock`, to control the timestamps in tests.

I imagine you'd create these listeners and pass them when creating the `Database`, with an empty list as the default argument.

If there's interest in this feature, I'd be happy to check out the code and try to add it.

**Comment by vincentlauvlwj** [comment]
Good idea, but it is difficult to implement in Ktorm. Consider the case of using SQL DSL, in which we don't need to create an `Entity` object before inserting it, then how can we call the listener without `Entity` object?

**Comment by JGulbronson** [comment]
Yeah that's a good point, but in that case you wouldn't have an `Entity` object to satisfy the method anyway. You're right it'd only get called when persisting an Entity, but that seems somewhat reasonable to me given the signature?

**Comment by vincentlauvlwj** [comment]
Close this issue because it is somewhat impossible to be done.
