### ISSUE TITLE
插入中文时乱码，手动执行生成语句则正常

### ISSUE THREAD

**Issue by HanaForward** [kotlin-orm/ktorm#244]
编码：utf8mb4
插入中文和特殊字符会变成 ? (0x3f)
生成的语句：
 SQL: insert into player (qq, name) values (?, ?) 
Parameters: [123456(varchar), 我熬(varchar)]

实际效果  name 会变成 0x3f 0x3f 也就是两个问号

**Comment by vincentlauvlwj** [comment]
这种问题跟 Ktorm 无关，检查你的数据库和环境配置

**Comment by HanaForward** [comment]
我手动执行这个指令是正常的，是不是连接配置有啥问题？
