### ISSUE TITLE
使用Maven开发，用实体绑定的时候，报java.lang.NoClassDefFoundError: kotlin/jvm/internal/KTypeBase

### ISSUE THREAD

**Issue by lvdong** [kotlin-orm/ktorm#245]
使用Maven 用实体绑定的时候，报java.lang.NoClassDefFoundError: kotlin/jvm/internal/KTypeBase，不用实体绑定的话能正常执行。我用的kotlin 1.4.21 ktorm是最新版

**Comment by vincentlauvlwj** [comment]
检查 Kotlin 的版本号，要求 1.4 以上

**Comment by vincentlauvlwj** [comment]
可能从别的地方引入了低版本的 Kotlin，注意依赖冲突
