### ISSUE TITLE
Change the pagination method "drop()" to "skip()"

### ISSUE THREAD

**Issue by metacubed** [kotlin-orm/ktorm#246]
The keyword `drop` is used for destructive operations in many database dialects:
```sql
drop table ...
drop schema ...
drop database ...
```

We can replace it with a pagination-oriented word, such as `skip`, `offset`, etc.

So, change this:
> val employees = database.employees.**<strike>drop(3)</strike>**.take(5).toList()

to this:
> val employees = database.employees.**skip(3)**.take(5).toList()

**Comment by vincentlauvlwj** [comment]
Kotlin collections use `drop`, I think it is better to follow the naming practice in Kotlin.

**Comment by metacubed** [comment]
Following Kotlin conventions is better - I agree with this reasoning.
