### ISSUE TITLE
[BUG] Ktorm no longer supports Postgresql DO NOTHING

### ISSUE THREAD

**Issue by FeatureSpitter** [kotlin-orm/ktorm#248]
Hello @vincentlauvlwj 

I remember we implemented this feature in this [PR](https://github.com/kotlin-orm/ktorm/pull/226).

In the feature of this commit, it was possible to do something like:

```kotlin
      database.bulkInsert(Employees) {
          item {
              set(it.id, 1)
              set(it.name, "vince")
              set(it.job, "engineer")
              set(it.salary, 1000)
              set(it.hireDate, LocalDate.now())
              set(it.departmentId, 1)
          }
          item {
              set(it.id, 5)
              set(it.name, "vince")
              set(it.job, "engineer")
              set(it.salary, 1000)
              set(it.hireDate, LocalDate.now())
              set(it.departmentId, 1)
          }

          onDuplicateKey(Employees.id) {
              // I am leaving this intentionally empty, so Postgresql will ignore this error and proceed inserting the others
             // INSERT INTO ... ON CONFLICT (employee_id) DO NOTHING
          }
      }
```

This behavior was tested in `ktorm-support-postgresql/src/test/kotlin/org/ktorm/support/postgresql/PostgreSqlTest.kt` function [testBulkInsertWithUpdate](https://github.com/kotlin-orm/ktorm/commit/72c24ed619ebd37cf0c5d9a8763340c32a121ed4#diff-1a23f6d150378f28c37a994c1d2aefd11573906ebe7175303fe587703b1a0f06R155). And implemented [here](https://github.com/kotlin-orm/ktorm/commit/72c24ed619ebd37cf0c5d9a8763340c32a121ed4#diff-0494b92e8f823ed1726b57c1aa0ab6caca3ab2a30586e34e8214c81d923c3dddR210).

This is the visitor function as you have it now:

```kotlin
   protected open fun visitInsertOrUpdate(expr: InsertOrUpdateExpression): InsertOrUpdateExpression {
        writeKeyword("insert into ")
        visitTable(expr.table)
        writeInsertColumnNames(expr.assignments.map { it.column })
        writeKeyword("values ")
        writeInsertValues(expr.assignments)

        if (expr.updateAssignments.isNotEmpty()) {
            writeKeyword("on conflict ")
            writeInsertColumnNames(expr.conflictColumns)
            writeKeyword("do update set ")
            visitColumnAssignments(expr.updateAssignments)
        }

        return expr
    }
```

This is how it should be in order to support the DO NOTHING feature that Postgresql provides, as we did in that PR:

```kotlin
    protected open fun visitInsertOrUpdate(expr: InsertOrUpdateExpression): InsertOrUpdateExpression {
        writeKeyword("insert into ")
        visitTable(expr.table)
        writeInsertColumnNames(expr.assignments.map { it.column })
        writeKeyword("values ")
        writeInsertValues(expr.assignments)

        if (expr.conflictColumns.isNotEmpty()) {
            writeKeyword("on conflict ")
            writeInsertColumnNames(expr.conflictColumns)
            
            if (expr.updateAssignments.isNotEmpty()) {
                writeKeyword("do update set ")
                visitColumnAssignments(expr.updateAssignments)
            } else {
                writeKeyword("do nothing ")
            }
        }

        return expr
    }
```

Also, not forgetting now about the returning feature as well, so the final function for 3.4.0 would actually be:

```kotlin
    protected open fun visitInsertOrUpdate(expr: InsertOrUpdateExpression): InsertOrUpdateExpression {
        writeKeyword("insert into ")
        visitTable(expr.table)
        writeInsertColumnNames(expr.assignments.map { it.column })
        writeKeyword("values ")
        writeInsertValues(expr.assignments)

        if (expr.conflictColumns.isNotEmpty()) {
            writeKeyword("on conflict ")
            writeInsertColumnNames(expr.conflictColumns)

            if (expr.updateAssignments.isNotEmpty()) {
                writeKeyword("do update set ")
                visitColumnAssignments(expr.updateAssignments)
            } else {
                writeKeyword("do nothing ")
            }
        }

        if (expr.returningColumns.isNotEmpty()) {
            writeKeyword(" returning ")
            expr.returningColumns.forEachIndexed { i, column ->
                if (i > 0) write(", ")
                checkColumnName(column.name)
                write(column.name.quoted)
            }
        }

        return expr
    }
```

Please can you fix this here and on the other Postgresql dialect functions where the DO NOTHING feature got removed?
I think it is only the `visitBulkInsert` function that needs this fix as well. Also the test that tested this feature (linked above) should be recovered as well.

PS. It doesn't seem like it, but this is an important feature which I see no reason to forbid Ktorm users from using it. As it is now, the user is always forced to unnecessarily update one column in order to get conflict errors ignored. This is not ideal in terms of performance.

**Comment by vincentlauvlwj** [comment]
I'm sorry for making this change without letting you know. 

This is because of a bug that I found in your PR. If I called the `onConflictKey` function without specifying the conflict columns, then the `on conflict` clause would be missed in the generated SQL. For example: 

```kotlin
database.bulkInsert(Employees) {
    item {
        set(it.id, 1)
        set(it.name, "vince")
        set(it.job, "engineer")
        set(it.salary, 1000)
        set(it.hireDate, LocalDate.now())
        set(it.departmentId, 1)
    }
    onDuplicateKey {
        set(it.salary, it.salary + 900)
    }
}
```

The generated SQL would be the following, without `on conflict` clause: 

```sql
insert into t_employee (id, name, job, salary, hire_date, department_id) values ( ?, ?, ?, ?, ?, ? )
```

To fix this bug, I had to use the primary keys as the conflict targets if they weren't specified: 

```kotlin
conflictTarget = builder.conflictColumns.ifEmpty { table.primaryKeys }.map { it.asExpression() }
```

But after I did this, I found another problem that `on conflict do nothing` would be always generated even if we didn't call `onDuplicateKey`. For code like this: 

```kotlin
database.bulkInsert(Employees) {
    item {
        set(it.id, 1)
        set(it.name, "vince")
        set(it.job, "engineer")
        set(it.salary, 1000)
        set(it.hireDate, LocalDate.now())
        set(it.departmentId, 1)
    }
}
```

The generated SQL would be: 

```sql
insert into t_employee (id, name, job, salary, hire_date, department_id) 
values ( ?, ?, ?, ?, ?, ? ) on conflict (id) do nothing
```

This was because we were using `confictTarget` to decide whether to generate the `on conflict` clause, but `conflictTarget` are always present as I use the primary keys by default. What a dilemma. 

Yes, you are right, this is an important feature, but if it can't be implemented perfectly, I would rather remove it temporarily. When we have a better solution, we can add it back.

**Comment by FeatureSpitter** [comment]
@vincentlauvlwj that's a nice catch.

I actually solved this recently in a local copy of Ktorm I was testing with, I did the following way:

If you never call `onDuplicateKey`, no `ON CONFLICT` will be generated, ever.

If you call `onDuplicateKey` without specifying the columns, it will use the primary keys just like you said.

If you call `onDuplicateKey` with columns, it will use those.

If you call `onDuplicateKey` without any assignments it will generate the `DO NOTHING`.

What do you think of this one?

**Comment by vincentlauvlwj** [comment]
> If you call onDuplicateKey without any assignments it will generate the DO NOTHING.

Would it be better to explicitly call a function like `doNothing()`, for example: 

```kotlin
database.bulkInsert(Employees) {
    item {
        set(it.id, 1)
        set(it.name, "vince")
        set(it.job, "engineer")
        set(it.salary, 1000)
        set(it.hireDate, LocalDate.now())
        set(it.departmentId, 1)
    }
    onDuplicateKey {
        doNothing()
    }
}
```

**Comment by vincentlauvlwj** [comment]
Supported in 3.4.0
