### ISSUE TITLE
Schema change on query level

### ISSUE THREAD

**Issue by skch-17** [kotlin-orm/ktorm#249]
This request addresses multi tenancy. When you have one database with multiple schemas, you need to change the schema on query level incase you have a service user.

**Comment by vincentlauvlwj** [comment]
Can provide a usage example that you imagine this feature should be?

**Comment by skch-17** [comment]
Sure i can do.

If a project needs to support multi tenancy, there are three main routes you can take:
1. Database per customer
2. Schema per customer
3. Data has a customer indicator on table.

As option one would be really nice, it will take a lot of code and effort to support. But should probably not even be on this layer.

Interesting is now option 2, because there is already schema support built in, but as with multi tenancy, you need to switch possibly on every request, thats why you need a way to set the schema on the query built time with a parameter.

Option three is already possible.

So I could imagine that the features syntax would look something like this:

database
    .from(Employees, "SchemaName")
    .leftJoin(Departments, on = Employees.departmentId eq Departments.id, "SchemaName")
    .select(Employees.name, Departments.name)
    .where { Employees.salary greater 100L }

So it would need a functionality to override the schema that is currently hard set on the table for the query. As you can see above, one should be able to set the schema on joining tables as well. Because a joining table could probably be on a different schema. (Not directly linked to a customer, like general information)

The schema name property would be optional to not mess with the nice syntax when not required.

Some concerns: 
I currently do not know the internals of this project, so it should be multi threading save. I am thinking about a web api case, where each web request has its own thread.

**Comment by vincentlauvlwj** [comment]
Actually option 2 is also possible.

Define your tables like this: 

```kotlin
class Departments(schema: String) : Table<Nothing>("t_department", schema = schema) {
    val id = int("id").primaryKey()
    val name = varchar("name")
    val location = varchar("location")
}

class Employees(schema: String) : Table<Nothing>("t_emplyee", schema = schema) {
    val id = int("id").primaryKey()
    val name = varchar("name")
    val job = varchar("job")
    val salary = long("salary")
    val departmentId = int("department_id")
}
```

Usage: 

```kotlin
val dept = Departments("schema_name")
val emp = Employees("schema_name")

database
    .from(emp)
    .leftJoin(dept, on = emp.departmentId eq dept.id)
    .select(emp.name, dept.name)
    .where { emp.salary greater 100L }
```

**Comment by skch-17** [comment]
Yea that works. Didn't think about that solution XD.

Thx
