### ISSUE TITLE
[Quick Help] CachedRowSet -> QueryRowSet

### ISSUE THREAD

**Issue by FeatureSpitter** [kotlin-orm/ktorm#250]
Hello @vincentlauvlwj !

I am trying to add a new `returning` function that further extends my last PR with the Postgresql `returning` functions, but I need your quick help here.

Context: So we have 3 flavors of these functions: One returning `R`, other `Pair<R1, R2>` and other `Triple<R1, R2, R3>`, correct?

What I want to add now is another function, returning `R: Entity<R>` :)

This is my implementation so far:

```kotlin
public fun <T : BaseTable<R>, R : Entity<R>> Database.bulkInsertOrUpdateReturning(
    table: T,
    block: BulkInsertOrUpdateStatementBuilder<T>.(T) -> Unit
): List<R> {
    val (_, rowSet) = this.bulkInsertOrUpdateReturningAux(
        table,
        table.columns, // We select all columns of this table so we can build the complete entity
        block
    )

    return rowSet.asIterable().map { row ->
        table.createEntity(row) // <------------ This is wrong here, it is where I am stuck
    }
}
```
I get the following error:

![image](https://user-images.githubusercontent.com/39516190/108347930-0d4e2880-71d9-11eb-98bc-11d6f1981278.png)

I understand what the error message means, but I have no idea how to convert a `CachedRowSet` into a `QueryRowSet`, specially because the constructor is private.

What's the best way to achieve this here?

Thanks!

**Comment by vincentlauvlwj** [comment]
This can't be implemented. `QueryRowSet` requires the results are obtained from a `Query`, but your case is an update, not a query.

**Comment by FeatureSpitter** [comment]
@vincentlauvlwj in theory it should be possible since the DB is returning the columns, and we implemented the other `returning` methods.

Other possible way: Is it possible to create an overload of the `createEntity` that accepts a `CachedRowSet` (or even better, a `List<Map<String, Any?>>` containing all the returned columns?
