### ISSUE TITLE
mysql-connector 8.0.23 下报异常：Cannot convert java.time.LocalDateTime value to Timestamp

### ISSUE THREAD

**Issue by ymind** [kotlin-orm/ktorm#252]
我找了一下，导致该bug的根源是：https://github.com/mysql/mysql-connector-j/commit/60553fd2557267f3184b77e1832025f80d79e89a#diff-66dbd292da670fea38bc452cd52efcc61c87859c02115a03df95a6204a0f6f40R1264-R1269

从mysql 驱动 8.0.23 之后，LocalDateTime 类型的字段会直接返回为 LocalDateTime 而不是之前的 Timestamp。这最终导致ktrom 3.3.0如下代码异常：
![image](https://user-images.githubusercontent.com/315716/108806979-293d3a00-75de-11eb-92dd-531b34b7d97e.png)

**Comment by vincentlauvlwj** [comment]
谢谢，下个版本兼容一下

**Comment by vincentlauvlwj** [comment]
3.4.0 版本已修复
