### ISSUE TITLE
ktorm 支持动态传字段查询吗? 

### ISSUE THREAD

**Issue by HarveyZh0218** [kotlin-orm/ktorm#262]
比如: 接口调用者 传入一个string类型字段, 然后进行查询该字段, 或者根据这个字段动态排序.

**Comment by vincentlauvlwj** [comment]
可以用 `table[name]` 根据字段名获取 `Column` 对象，得到之后你想用来查询还是排序都可以

**Comment by HarveyZh0218** [comment]
好的,多谢.
