### ISSUE TITLE
Hibernate Validator 是否支持

### ISSUE THREAD

**Issue by king54346** [kotlin-orm/ktorm#264]
由于不是实体类而是interface数据校验的注解是无法使用的，我也知道可以使用实体类，但是还是想知道作者是如何解决interface无法使用注解的

**Comment by vincentlauvlwj** [comment]
不支持，我不知道有什么场景是需要对 Ktorm 的对象做这种校验，因为一般来说，与外界交互，我们会使用专门的 DTO 对象，而不是直接吧持久层的实体对象暴露出去
