### ISSUE TITLE
Auto left join with BaseTable?

### ISSUE THREAD

**Issue by P1NG2WIN** [kotlin-orm/ktorm#266]
Is it possible to specify references to a field in BaseTable?

The `UsersTable` has a `cityId` field that is specified as a foreign key to the `CitiesTable`, the `id `field, in mysql.

When doing `doCreateEntity`, I want to create the city object as `CitiesTable.createEntity(row)` (`user.city = CitiesTable.createEntity(row)`). Right now I manually add `leftJoin (CItiesTable, on = UsersTable.cityId eq CitiesTable.id)` for any select

**Comment by vincentlauvlwj** [comment]
You can write an extension function by yourself to avoid this code repeatation: 

```kotlin
fun Database.fromUsersTable(): Query {
    return this
        .from(UsersTable)
        .leftJoin(CitiesTable, on = UsersTable.cityId eq CitiesTable.id)
        .select(UsersTable.columns + CitiesTable.columns)
}
```

Usage: 

```kotlin
val query = database.fromUsersTable().where { ... }
```
