### ISSUE TITLE
Allow choosing constraint name in insertOrUpdate

### ISSUE THREAD

**Issue by Liczi** [kotlin-orm/ktorm#267]
The `insertOrUpdate` function for PostgreSQL ([docs](https://www.ktorm.org/api-docs/org.ktorm.support.postgresql/insert-or-update.html)) is using `on conflict` statement which takes the constraint name as a parameter. It is hardcoded to use PK at the moment. Allowing to pass a constraint name optionally is needed to use `insertOrUpdate` with tables that use an artificial primary key. I assume this behavior is similar in other databases.

**Comment by vincentlauvlwj** [comment]
It's already supported for PostgreSQL: 

```kotlin
database.insertOrUpdate(Employees) {
    set(it.id, 5)
    set(it.name, "vince")
    set(it.job, "engineer")
    set(it.salary, 1000)
    set(it.hireDate, LocalDate.now())
    set(it.departmentId, 1)
    onConflict(it.id) { // You can specify any columns here...
        set(it.salary, it.salary + 1000)
    }
}
```

**Comment by Liczi** [comment]
thanks @vincentlauvlwj I missed that...
