### ISSUE TITLE
能否支持多数据源的“left join”

### ISSUE THREAD

**Issue by llaiajiale** [kotlin-orm/ktorm#269]
能否使用多条SQL语句来替代left join
出现关联关系的从新生成一条sql去查询。支持多数据源
如：
select * 
from t_employee 
left join t_department _ref0 on t_employee.department_id = _ref0.id 
where employee_id = ?
替换为
MYSQL:   select * from t_employee where employee_id = ?
ORACLE:  select * from t_department where id in ( ? )

**Comment by vincentlauvlwj** [comment]
参考这个 issue https://github.com/kotlin-orm/ktorm/issues/83

**Comment by llaiajiale** [comment]
> 
> 
> 参考这个 issue #83

无法找到findList方法。需要安装扩展吗?

**Comment by vincentlauvlwj** [comment]
那个是旧版本的代码，新版本改成 `database.employees.filter { it.departmentId eq id }.toList()`

**Comment by llaiajiale** [comment]
> 
> 
> 那个是旧版本的代码，新版本改成 `database.employees.filter { it.departmentId eq id }.toList()`

感谢大神，我已经改源码实现了我的需求。现在的find方法只需要传入主键无需进行字段匹配，关联关系也通过扩展函数实现了，感谢。
附上代码供大家参考。
        val staffSequence = database.sequenceOf(Staffs);
        val staffs = staffSequence.take(10).toList();
        staffs.load(Staff::company, Staff::comcode)


public inline fun <E : Entity<*>> List<E>.load(property: KProperty1<E, *>,
                                      withProperity: KProperty1<E, *>) {
    if(size>0){
        val first : E = get(0);
        val method = first.javaClass.kotlin.declaredFunctions.filter { it.name.equals(property.name) }.firstOrNull()

        if(method == null)
            throw NoSuchMethodException("can not find the method[${property.name}] from class[${first.javaClass.name}].")

        val keys = map { withProperity.get(it) }.distinct()

        val es = method.call(first)
        if(es is EntitySequence<*, *>){
            val primaryKeys = es.sourceTable.primaryKeys
            if (primaryKeys.isEmpty()) {
                throw UnsupportedOperationException("Table [${es.sourceTable.tableName}] doesn't have a primary key.")
            }
            if (primaryKeys.size > 1) {
                throw UnsupportedOperationException("Table [${es.sourceTable.tableName}] have ${primaryKeys.size} primary keys.")
            }
            val pk = primaryKeys[0]
            var cd :ColumnDeclaring<Boolean> =
                when(pk.sqlType){
                    is VarcharSqlType -> pk.cast(VarcharSqlType).inList(keys as Collection<String>)
                    is IntSqlType ->  pk.cast(IntSqlType).inList(keys as Collection<Int>)
                    is LongSqlType -> pk.cast(LongSqlType).inList(keys as Collection<Long>)
                    else -> throw UnsupportedOperationException("${pk.sqlType} was not matched ${keys.javaClass}")
                }


            val references = es.database.from(es.sourceTable).select().where { cd }
                .map { row -> es.entityExtractor(row)  } as List<Entity<*>>
            val map = references.groupBy { it.get(pk.name) }
            if(property.returnType is List<*>){
                for (i in indices){
                    val e : E = get(i)
                    val ref = withProperity.get(e)
                    e.set(property.name, map[ref])
                }
            } else {
                for (i in indices){
                    val e : E = get(i)
                    val ref = withProperity.get(e)
                    val values = map[ref]
                    if(values != null){
                        e.set(property.name, values.get(0))
                    } else {
                        e.set(property.name, null)
                    }
                }
            }
        }
    }
}

**Comment by vincentlauvlwj** [comment]
用这个 load 函数的话，实体类要怎么定义呢？

**Comment by llaiajiale** [comment]
只能1对多的简单嵌套，有中间表的映射还不行。

```

interface Staff : Entity<Staff> {
    val usercode: String
    val username: String
    val comcode: String

    val company : Company?
        get() = this.company().filter { it.comcode eq comcode }.firstOrNull()


    fun company() : EntitySequence<Company, Companies> {
        return Database.readOf(Staffs))
    }
}

@DatabaseConfig(read = "ai-read@dataBase", write = "ai-write@dataBase")
object Staffs : UcBaseBindTable<Staff>("table_staffs") {
	.....
}
```

**Comment by llaiajiale** [comment]
> 
> 
> 用这个 load 函数的话，实体类要怎么定义呢？

再请教一下，一个多对多的关联关系怎么生成啊。涉及到一张中间表。比如Staff拥有多个Roles，通过table_staff_role进行关联。
