### ISSUE TITLE
请问怎么兼容 swagger ui 

### ISSUE THREAD

**Issue by chenjianche** [kotlin-orm/ktorm#270]
我的实体类
@ApiModel("项目类")
interface Project:Entity<Project> {
    companion object:Entity.Factory<Project>()
    //@ApiModelProperty("id")
    var id: Int
    //@ApiModelProperty("项目名称")
    var name: String
    //@ApiModelProperty("包名")
    var packageName: String
    //@ApiModelProperty("创建时间")
    var createDate: LocalDateTime
}
下面是swagger 生成的接口文档，里面好多 Entity 里的东西，而且interface里 也没办法写@ApiModelProperty
`{
  "createDate": "2021-04-10T04:20:35.204Z",
  "entityClass": {
    "abstract": true,
    "annotations": [
      {}
    ],
    "companion": true,
    "constructors": [
      {
        "abstract": true,
        "annotations": [
          {}
        ],
        "external": true,
        "final": true,
        "infix": true,
        "inline": true,
        "name": "string",
        "open": true,
        "operator": true,
        "parameters": [
          {
            "annotations": [
              {}
            ],
            "index": 0,
            "kind": "INSTANCE",
            "name": "string",
            "optional": true,
            "type": {
              "annotations": [
                {}
              ],
              "arguments": [
                {
                  "variance": "INVARIANT"
                }
              ],
              "classifier": {},
              "markedNullable": true
            },
            "vararg": true
          }
        ],
        "returnType": {
          "annotations": [
            {}
          ],
          "arguments": [
            {
              "variance": "INVARIANT"
            }
          ],
          "classifier": {},
          "markedNullable": true
        },
        "suspend": true,
        "typeParameters": [
          {
            "name": "string",
            "reified": true,
            "upperBounds": [
              {
                "annotations": [
                  {}
                ],
                "arguments": [
                  {
                    "variance": "INVARIANT"
                  }
                ],
                "classifier": {},
                "markedNullable": true
              }
            ],
            "variance": "INVARIANT"
          }
        ],
        "visibility": "PUBLIC"
      }
    ],
    "data": true,
    "final": true,
    "fun": true,
    "inner": true,
    "members": [
      {
        "abstract": true,
        "annotations": [
          {}
        ],
        "final": true,
        "name": "string",
        "open": true,
        "parameters": [
          {
            "annotations": [
              {}
            ],
            "index": 0,
            "kind": "INSTANCE",
            "name": "string",
            "optional": true,
            "type": {
              "annotations": [
                {}
              ],
              "arguments": [
                {
                  "variance": "INVARIANT"
                }
              ],
              "classifier": {},
              "markedNullable": true
            },
            "vararg": true
          }
        ],
        "returnType": {
          "annotations": [
            {}
          ],
          "arguments": [
            {
              "variance": "INVARIANT"
            }
          ],
          "classifier": {},
          "markedNullable": true
        },
        "suspend": true,
        "typeParameters": [
          {
            "name": "string",
            "reified": true,
            "upperBounds": [
              {
                "annotations": [
                  {}
                ],
                "arguments": [
                  {
                    "variance": "INVARIANT"
                  }
                ],
                "classifier": {},
                "markedNullable": true
              }
            ],
            "variance": "INVARIANT"
          }
        ],
        "visibility": "PUBLIC"
      }
    ],
    "nestedClasses": [
      {
        "abstract": true,
        "annotations": [
          {}
        ],
        "companion": true,
        "constructors": [
          {
            "abstract": true,
            "annotations": [
              {}
            ],
            "external": true,
            "final": true,
            "infix": true,
            "inline": true,
            "name": "string",
            "open": true,
            "operator": true,
            "parameters": [
              {
                "annotations": [
                  {}
                ],
                "index": 0,
                "kind": "INSTANCE",
                "name": "string",
                "optional": true,
                "type": {
                  "annotations": [
                    {}
                  ],
                  "arguments": [
                    {
                      "variance": "INVARIANT"
                    }
                  ],
                  "classifier": {},
                  "markedNullable": true
                },
                "vararg": true
              }
            ],
            "returnType": {
              "annotations": [
                {}
              ],
              "arguments": [
                {
                  "variance": "INVARIANT"
                }
              ],
              "classifier": {},
              "markedNullable": true
            },
            "suspend": true,
            "typeParameters": [
              {
                "name": "string",
                "reified": true,
                "upperBounds": [
                  {
                    "annotations": [
                      {}
                    ],
                    "arguments": [
                      {
                        "variance": "INVARIANT"
                      }
                    ],
                    "classifier": {},
                    "markedNullable": true
                  }
                ],
                "variance": "INVARIANT"
              }
            ],
            "visibility": "PUBLIC"
          }
        ],
        "data": true,
        "final": true,
        "fun": true,
        "inner": true,
        "members": [
          {
            "abstract": true,
            "annotations": [
              {}
            ],
            "final": true,
            "name": "string",
            "open": true,
            "parameters": [
              {
                "annotations": [
                  {}
                ],
                "index": 0,
                "kind": "INSTANCE",
                "name": "string",
                "optional": true,
                "type": {
                  "annotations": [
                    {}
                  ],
                  "arguments": [
                    {
                      "variance": "INVARIANT"
                    }
                  ],
                  "classifier": {},
                  "markedNullable": true
                },
                "vararg": true
              }
            ],
            "returnType": {
              "annotations": [
                {}
              ],
              "arguments": [
                {
                  "variance": "INVARIANT"
                }
              ],
              "classifier": {},
              "markedNullable": true
            },
            "suspend": true,
            "typeParameters": [
              {
                "name": "string",
                "reified": true,
                "upperBounds": [
                  {
                    "annotations": [
                      {}
                    ],
                    "arguments": [
                      {
                        "variance": "INVARIANT"
                      }
                    ],
                    "classifier": {},
                    "markedNullable": true
                  }
                ],
                "variance": "INVARIANT"
              }
            ],
            "visibility": "PUBLIC"
          }
        ],
        "nestedClasses": [
          null
        ],
        "objectInstance": {},
        "open": true,
        "qualifiedName": "string",
        "sealed": true,
        "sealedSubclasses": [
          null
        ],
        "simpleName": "string",
        "supertypes": [
          {
            "annotations": [
              {}
            ],
            "arguments": [
              {
                "variance": "INVARIANT"
              }
            ],
            "classifier": {},
            "markedNullable": true
          }
        ],
        "typeParameters": [
          {
            "name": "string",
            "reified": true,
            "upperBounds": [
              {
                "annotations": [
                  {}
                ],
                "arguments": [
                  {
                    "variance": "INVARIANT"
                  }
                ],
                "classifier": {},
                "markedNullable": true
              }
            ],
            "variance": "INVARIANT"
          }
        ],
        "visibility": "PUBLIC"
      }
    ],
    "open": true,
    "qualifiedName": "string",
    "sealed": true,
    "sealedSubclasses": [
      null
    ],
    "simpleName": "string",
    "supertypes": [
      {
        "annotations": [
          {}
        ],
        "arguments": [
          {
            "variance": "INVARIANT"
          }
        ],
        "classifier": {},
        "markedNullable": true
      }
    ],
    "typeParameters": [
      {
        "name": "string",
        "reified": true,
        "upperBounds": [
          {
            "annotations": [
              {}
            ],
            "arguments": [
              {
                "variance": "INVARIANT"
              }
            ],
            "classifier": {},
            "markedNullable": true
          }
        ],
        "variance": "INVARIANT"
      }
    ],
    "visibility": "PUBLIC"
  },
  "id": 0,
  "name": "string",
  "packageName": "string",
  "properties": {}
}`
只有 id、name、packageName、createDate 是我的属性。

**Comment by vincentlauvlwj** [comment]
注解这样写：

```kotlin
@get:ApiModelProperty("id")
var id: Int
```

另外，注意排版...

**Comment by chenjianche** [comment]
不好意思第一次在github上提问,还不太会弄。
interface可以了，就是父类的 entityClass、properties 两个属性还不知道怎么隐藏。
