### ISSUE TITLE
使用any函数出现type error

### ISSUE THREAD

**Issue by EvanLuo42** [kotlin-orm/ktorm#272]
代码如下:
`val users: Sequence<Users> = sequenceOf(Users)
 if(users.any { Users.user_id eq "vince" })`
出现如下错误:
`Type mismatch.
Required: Boolean
Found: BinaryExpression<Boolean>`
请问该如何更改？

**Comment by vincentlauvlwj** [comment]
这个 `sequenceOf` 函数是你自己写的吗

**Comment by EvanLuo42** [comment]
用的kotlin.sequence里的。因为文档里用定义扩展属性的方法我用起来有点问题。

**Comment by EvanLuo42** [comment]
已经解决了，谢谢
