### ISSUE TITLE
null value is not considered, when a default value is generated in a nullable column

### ISSUE THREAD

**Issue by Valefant** [kotlin-orm/ktorm#273]
I set `lastMaintenance` to `null`
![image](https://user-images.githubusercontent.com/19901781/114312180-0b765680-9af2-11eb-9734-3cac0738724b.png)

Here is my table definition. See that nullable values are allowed for the column `last_maintenance`.
![image](https://user-images.githubusercontent.com/19901781/114311899-ed5c2680-9af0-11eb-949c-8190f34c1fa9.png)

This is the result I got when the row was inserted
![image](https://user-images.githubusercontent.com/19901781/114311808-8a6a8f80-9af0-11eb-912f-8167ce17ddb6.png)

`EntityDml` -> `findInsertColumns#216`. `null` values seem to be skipped, but in my case it would be valid to insert null.
![image](https://user-images.githubusercontent.com/19901781/114311853-b84fd400-9af0-11eb-8a33-e26e1e2baaf8.png)

**Comment by vincentlauvlwj** [comment]
Thank you. Will fix it in the future.

**Comment by vincentlauvlwj** [comment]
Fixed in 3.4.0

**Comment by wtksana** [comment]
这个竟然算是bug吗  我以为是特性呢
我项目里大量用到这个特性。。从3.3.0版本升级到3.4.1后全面报错。。。

**Comment by vincentlauvlwj** [comment]
@wtksana Yes, this should be a bug.

**Comment by vincentlauvlwj** [comment]
@wtksana 但是这个修改确实是不兼容的，抱歉给你们造成麻烦

**Comment by wtksana** [comment]
@vincentlauvlwj  我旧的项目决定还是不升级了 新项目用新的版本开发 
bug是无法避免的 ktorm给我的开发带来了极大的便利 感谢
