### ISSUE TITLE
怎么实现属性的默认值

### ISSUE THREAD

**Issue by xcore-oss** [kotlin-orm/ktorm#274]
怎么实现属性的默认值
例如我有一个排序字段:
var orderBy: Int
我希望在我不设置他的时候新增结果为0
更新的时候又可以手动设置

**Comment by vincentlauvlwj** [comment]
在 SQL 建表语句里面写 `column_name integer not null default 0`

**Comment by xcore-oss** [comment]
你理解错我的意思了
现在的问题是我实例化接口字段赋值的问题

**Comment by vincentlauvlwj** [comment]
详细描述你的问题

**Comment by xcore-oss** [comment]
例如我需要实例化一个对象,但是我直给部分字段赋值,剩余的可空字段或值类型字段会自动为默认值而不是报值不能为null的错
还有我希望可以设置某个字段的值为数据库函数,例如时间类型,我希望的赋值方式是数据库当前时间而不是系统当前时间

**Comment by vincentlauvlwj** [comment]
可以用代码来更好地描述你的需求
