### ISSUE TITLE
请教是否有类似getOne()返回QueryRowSet单条记录的办法

### ISSUE THREAD

**Issue by yoonching** [kotlin-orm/ktorm#279]
作者您好，首先感谢您辛苦的付出，这款ktorm上手很快，使得我最近从0开始学kotlin做学习项目时很顺滑。

我想请教两个问题：

1、是否有类似getOne的方法，只返回一条QueryRowSet记录？目前我是自己写了个方法去筛选出来1条。

2、是否有能把QueryRowSet直接转成HashMap的方式呢？

以上。刚开始接触kotlin，并且翻阅了ktorm的源码，没有找到相关答案，在此提问，还请不吝赐教。

**Comment by HarveyZh0218** [comment]
// 返回一条记录
.firstOrNull()

// 返回Map  //不知道对不对 没测试
.associate { Pair(it.getString(1), it.getString(2)) }

**Comment by vincentlauvlwj** [comment]
@yoonching 不是很明白你的问题，最好用代码说明一下

**Comment by ghostg00** [comment]
他的第二个问题应该是  Query 查询结果 那个 能不能直接转化为 List<Map> 这个意思吧?  

 @vincentlauvlwj 
 还有 作者大佬 ,我自己有几个问题     
 1.不知道  定义数据库字段的时候   是否 可以更可能的简单  例如    var name = varchar()    这样代替 var name = varchar("name")  默认 取属性名下划线 或者 属性名 
 2.还有 那个bindTo  是否可以直接默认绑定  到Entity类 上去 ,不需要额外定义 bindto呢  只有在自定义可选配置bindTo
 3. 自己写了下  感觉又要定义表结构 又要定义实体类  有些繁琐 而且 属性名都是一样的 , 是否能像类似jpa 或者mybatis plus 那样 把entity 和 table 合并成一个 类呢 ,可能这样需要借助注解了, 这样少去一些定义  写起来更方便些
  谢谢 大佬

**Comment by yoonching** [comment]
> @yoonching 不是很明白你的问题，最好用代码说明一下

我想您楼上的解答基本解决了我的问题。多谢！
