### ISSUE TITLE
关于 表定义的几个问题  请教一下

### ISSUE THREAD

**Issue by ghostg00** [kotlin-orm/ktorm#280]
1.不知道  定义数据库字段的时候   是否 可以更可能的简单  例如    var name = varchar()    这样代替 var name = varchar("name")  默认 取属性名下划线 或者 属性名 
 2.还有 那个bindTo  是否可以直接默认绑定  到Entity类 上去 ,不需要额外定义 bindto呢  只有在自定义可选配置bindTo
 3. 自己写了下  感觉又要定义表结构 又要定义实体类  有些繁琐 而且 属性名都是一样的 , 是否能像类似jpa 或者mybatis plus 那样 把entity 和 table 合并成一个 类呢 ,可能这样需要借助注解了, 这样少去一些定义  写起来更方便些
  谢谢 大佬

_Originally posted by @ghostg00 in https://github.com/kotlin-orm/ktorm/issues/279#issuecomment-827661257_

**Comment by ghostg00** [comment]
querydsl 的方式其实写起来也算简单  但是需要生成辅助类  不知道能不能更简单,也不需要生成额外的类来实现更简洁 更清晰的 定义   辛苦大佬了

**Comment by vincentlauvlwj** [comment]
不同的方式都有各自的优缺点，重点是看怎么权衡：

1. 像 JPA 那样只定义实体类的话，就难以实现 SQL DSL 和 Entity Sequence，而这正是 Ktorm 的核心功能
2. 像 querydsl 那样的话，就过于依赖代码生成了，我希望 Ktorm 能够尽可能地“轻”，其中一点就表现在只需要添加依赖就好，不需要任何的其他配置（代码生成器的插件也是一种配置）

为了解决你提的这些问题，未来 Ktorm 应该还是会提供代码生成插件，但是只会作为额外的小工具来提供，而不会进入核心代码库成为 Ktorm 功能的一部分

**Comment by ghostg00** [comment]
OK 谢谢大佬讲解 , 确实 ktorm 做到了 很轻,  只要引入数据源就可以了 无序额外配置   👍
