### ISSUE TITLE
请问下是否支持mybatis-plus那种注解式的逻辑删和乐观锁

### ISSUE THREAD

**Issue by codeStarry** [kotlin-orm/ktorm#281]

**Comment by vincentlauvlwj** [comment]
当然支持，但是 Ktorm 不用注解

**Comment by codeStarry** [comment]
@vincentlauvlwj 用DSL或实体序列嘛？？？

**Comment by vincentlauvlwj** [comment]
所谓乐观锁，无非就是使用一个类似版本号的字段，在更新时通过 `where` 条件限定一个条件，所以用 DSL 就可以做到，比如：

```kotlin
val effects = database.update(Employees) {
    set(it.salary, it.salary + 100)
    where { 
        (it.id eq 123) and (it.version eq 321) 
    }
}
```

这个方法的返回值是成功更新的记录数，因此可以通过 `effects` 来判断是否成功，如果 `effects > 0` 则更新成功；否则失败，可以抛出异常或者循环重试

这不就是乐观锁吗

**Comment by codeStarry** [comment]
嗯嗯，晓得了；我就是想像mybatis-plus一样的，只需在实体类中的相应属性加上相关注解，之后我只需要写实体序列或者DSL就行，乐观锁和逻辑删的部分由框架自动判断添加
