### ISSUE TITLE
请教是否支持外键一对多查询

### ISSUE THREAD

**Issue by yuzd** [kotlin-orm/ktorm#290]
比如有2个表

class 班级表
student 学生表

class 和 student  的关系是 1 ：N

那定义表结构的时候好像也没有办法搞这种一对多的把

在class 里面 定义一个 studen list的，我试了references 好像不行

会涉及到dsl会生成多个sql，应该目前不支持对吧

**Comment by vincentlauvlwj** [comment]
参考 #83, #283
