### ISSUE TITLE
集成在spring boot如何格式化日期呢？

### ISSUE THREAD

**Issue by watsonhaw5566** [kotlin-orm/ktorm#291]
![image](https://user-images.githubusercontent.com/4210367/118770121-87af4700-b8b3-11eb-9137-842a3d8eb9f5.png)
数据了是这样的，里面的文件我是模仿您ktorm-example-spring-boot中参考写的

![image](https://user-images.githubusercontent.com/4210367/118753126-e5816600-b896-11eb-94a4-59972aaf2f0b.png)
这里返回的日期是带T的时间
我在spring的配置中配置了jackson的日期格式化配置，重启了几次也没生效。
![image](https://user-images.githubusercontent.com/4210367/118753155-f5994580-b896-11eb-8614-b2b7bec3f82c.png)

我需要怎么配置才可以呢？
有空麻烦您解答一下，谢谢您

运行环境
系统:macOS 10.15.7
Spring版本:2.4.5
kotlin版本:1.4.32
Ktorm版本: 3.4.0

**Comment by vincentlauvlwj** [comment]
这个是 Spring Boot 的问题，不是 Ktorm 的问题，照理说不应该在这里提问。不过我帮你百度了一篇文章，你可以参考一下如何配置 https://www.cnblogs.com/carrychan/p/9883172.html

**Comment by watsonhaw5566** [comment]
> 因为 `spring.jackson.date-format` 这个配置只支持 `java.util.Date`，不支持 Java 8 的日期类型。
> 
> 这个是 Spring Boot 的问题，不是 Ktorm 的问题，照理说不应该在这里提问。不过我帮你百度了一篇文章，你可以参考一下如何配置 https://www.cnblogs.com/carrychan/p/9883172.html

感谢你的回复，我昨天弄完回去也想了一下是Java8的LocalDateTime的问题
