### ISSUE TITLE
spring boot前端传入时间字符串，无法自动转换为LocalDate

### ISSUE THREAD

**Issue by lvfengxian2021** [kotlin-orm/ktorm#293]
@GetMapping(value = ["/condition2"])
    fun condition2(loginInfo: KLoginInfor): List<KLoginInfor>? {
}

if (time != null) {
                        it += KLoginInfors.loginTime eq time
                    }
比较无效

**Comment by lvfengxian2021** [comment]
shema：
//登录日志 ,描述表结构,也是实体类，
interface KLoginInfor : Entity<KLoginInfor> {
    companion object : Entity.Factory<KLoginInfor>()
    //  id可以设置为空，如果不为空，获取的时候会报错
    var infoId: Long?
    var userName: String   //
    var loginLocation: String  //
    var browser: String
    var os: String
    var status: String
    var msg: String

    var loginTime: LocalDate
    var updBy: String
    var crtBy: String
    var crtTm: LocalDate
    var updTm: LocalDate

}
//表对象，相当于实体类的集合
open  class  KLoginInfors(alias: String?) : Table<KLoginInfor>("sys_logininfor",alias) {
    override fun aliased(alias: String) = KLoginInfors(alias)
    companion object : KLoginInfors(null)//伴随对象，作为未赋予别名的默认表对象，这样既支持了原来的写法，又能使用表别名的功能
    var infoId  = long("info_id").primaryKey().bindTo { it.infoId }
    var userName = varchar("user_name").bindTo { it.userName }
    var loginLocation = varchar("login_location").bindTo { it.loginLocation }
    var browser = varchar("browser").bindTo { it.browser }
    var os = varchar("os").bindTo { it.os }
    var status = varchar("status").bindTo { it.status }
    var msg = varchar("msg").bindTo { it.msg }
    var loginTime = date("login_time").bindTo { it.loginTime }
    var updBy = varchar("upd_by").bindTo { it.updBy }
    var crtBy = varchar("crt_by").bindTo { it.crtBy }
    var crtTm = date("crt_tm").bindTo { it.crtTm }
    var updTm = date("upd_tm").bindTo { it.updTm }

}

val Database.kLoginInfors get() = this.sequenceOf(KLoginInfors)

接口地址：http://127.0.0.1:9181/test/ktorm/condition2?pageNum=1&pageSize=10&infoId=55&userName=lvbu&loginTime=2021-05-20

   @GetMapping(value = ["/condition"])
    fun condition(loginInfo: KLoginInfor): List<KLoginInfor>? {
        val pageDomain =getPage()
        val offset = (pageDomain.pageNum-1)*10
        val list = database
                .from(KLoginInfors)
                .select()
                .where {
                    (KLoginInfors.infoId eq loginInfo.infoId!!) and (KLoginInfors.userName like "%"+loginInfo.userName+"%")
                }
                .limit(offset, pageDomain.pageSize)
                .orderBy(KLoginInfors.infoId.desc())
                .map { row -> KLoginInfors.createEntity(row) }
        return list
    }
loginTime是KLoginInfor的属性，前端出入的是字符串“2021-05-20”，KLoginInfor中的loginTime是LocalDate类型，会报错
Failed to convert from type [java.lang.String] to type [java.time.LocalDate] for value '2021-05-20'

==================
问题2：时间类型LocalDate无法在whereWithConditions闭包中比较

 @GetMapping(value = ["/condition2"])
    fun condition2(loginInfo: KLoginInfor): List<KLoginInfor>? {
        val loginTimeStr = ServletUtil.getParameter("time")
        val time = LocalDate.parse("2021-05-20", DateTimeFormatter.ofPattern("yyyy-MM-dd"));

        val pageDomain =getPage()
        val offset = (pageDomain.pageNum-1)*10

        val list = database
                .from(KLoginInfors)
                .select()
                .whereWithConditions {
    
                    if (time != null) {
                        it += KLoginInfors.loginTime eq time
                    }
                }
                .limit(offset, pageDomain.pageSize)
                .orderBy(KLoginInfors.infoId.desc())
                .map { row -> KLoginInfors.createEntity(row) }
        return list
    }
即使sys_logininfor表中有loginTime 值为2021-05-20，加入    it += KLoginInfors.loginTime eq time条件查询出的结果是空的

**Comment by vincentlauvlwj** [comment]
不要把 Ktorm 的实体类作为 Spring MVC 的参数，这样是不行的：

```kotlin
@GetMapping(value = ["/condition2"])
fun condition2(loginInfo: KLoginInfor)
```
