### ISSUE TITLE
Using custom functions in Database.insert

### ISSUE THREAD

**Issue by tox1cozZ** [kotlin-orm/ktorm#297]
Simple insert:
![image](https://user-images.githubusercontent.com/7694196/120905491-01d51f00-c65b-11eb-9447-8f35c2a70eab.png)
And custom insertPassword function:
![image](https://user-images.githubusercontent.com/7694196/120905509-1dd8c080-c65b-11eb-9347-ab0edf59182f.png)
Exception:
![image](https://user-images.githubusercontent.com/7694196/120905514-347f1780-c65b-11eb-9e0a-8cf1790e542f.png)
Why cast to ArgumentExpression?
![image](https://user-images.githubusercontent.com/7694196/120905525-4eb8f580-c65b-11eb-957a-4da8a3007ba1.png)

**Comment by vincentlauvlwj** [comment]
It's a bug, will fix in next version.

**Comment by vincentlauvlwj** [comment]
Fixed in 3.5.0
