### ISSUE TITLE
Question about filters dynamic

### ISSUE THREAD

**Issue by yael-lorenzo** [kotlin-orm/ktorm#298]
Hello ,

I am working on an idea around filters. Something like
```
    fun findAllWhere(filters: Set<Filter>): List<Review> {
        var query = database().reviews

        for (filter in filters) {
            query.filter { it.reflection_access_property eq filter.value }
        }
  }
```

However I get
`Cannot access 'eq': it is private in file`

Any hint on how to work with this dynamic way of adding filters?

**Comment by vincentlauvlwj** [comment]
What's `it.reflection_access_property `?

**Comment by yael-lorenzo** [comment]
The `reflection_access_property` is just an example trying to access the correct column on the table to make the `eq` comparison. 
I have to know the properties I am dealing with in order to evaluate if the filter can be set. 
Let's say I have the Filter class as
```
class Filter(
        val id: String,
        val propertyName: String,
        val value: String
)
```

and when I iterate on the filters I check if the property exists on the query filter as a column.
If it does exists I will apply the filter

Somthing like
```
fun findAllWhere(filters: Set<Filter>): List<Review> {
        var query = database().reviews
        for (filter in filters) {
            val property = p.javaClass.kotlin.members.any { it.name == "name" }
            if (property != null) 
                    query.filter { it.property eq filter.value }
        }
  }
```

**Comment by yael-lorenzo** [comment]
I have sort of bypassed this with

```
fun findAllWhere(filters: Set<Filter>): List<Review> {
        var query = database().reviews
        for (filter in filters) {
            var col = Reviews.get(filter.propertyName) as Column<Any>
            query = query.filter {  col eq filter.value }
        }

        return query.toList()
    }
```

**Comment by vincentlauvlwj** [comment]
Yes, you are right.
