### ISSUE TITLE
请教下Ktorm是否会出类似PageHelper的工具

### ISSUE THREAD

**Issue by Peter-So** [kotlin-orm/ktorm#301]
原有的SSM项目打算把Mybatis换成Ktorm，但是查看了文档只有分页方法。原有项目的pagehelper相关的参数都没有，如果都要手动计算工作量，重复工作太多了，是否会出类似PageHelper的工具把查询结果包装装page对象
另外原有项目用的是java对象返回，ktorm返回的是kt对象，有简单的方法可以把ktorm返回值转换成原有的java对象和数组吗？

**Comment by vincentlauvlwj** [comment]
分页可以参考 https://github.com/kotlin-orm/ktorm-example-spring-boot/blob/master/src/main/kotlin/org/ktorm/example/controller/EmployeeController.kt

**Comment by Peter-So** [comment]
好的，我参考下
