### ISSUE TITLE
Suggestion: Add notNullable() to table definitions to validate not nullable data mutation.

### ISSUE THREAD

**Issue by dave08** [kotlin-orm/ktorm#304]
Say one tries to `set(name, null)` on a `name` field that isn't nullable, there's currently no check that will show that while coding. Whereas if one tries to use `set` to set an `Int` value to a `varchar` field, the `set` function is deprecated... It would be nice to have something similar for non-nullable fields. And `notNullable()` shouldn't break the current definitions, since the current version treats every field as nullable by default.

**Comment by vincentlauvlwj** [comment]
I've already thought about this one year ago, but it's not that easy as you imagine. To perfectly achieve this, we have to refactor the whole code base... 😿

**Comment by dave08** [comment]
I don't know if it really needs to be perfect, currently there aren't any visual queues about accidently putting null where not allowed, even if it would be a visual warning like a deprecation or something, it would still be nice...
