### ISSUE TITLE
Where Function for Entity Update API

### ISSUE THREAD

**Issue by Arrowsome** [kotlin-orm/ktorm#306]
Hi, Based on the documentation updating with entity api is:

```kotlin
val employee = Employee {
    id = 5
    job = "engineer"
    salary = 100
}

database.employees.update(employee)
```
I haven't found a way to add a where clause and that leads to the problem of only being able to update based on the primary key.

How can something like this be done through entity API without the need of quering all data first and flushing changes:

```kotlin
db.update(AuthTable) {
    set(it.retryCount, it.retryCount + 1)
    where { (it.email eq email) and (it.retryCount less 4) }
}
```

Unlike DSL API, I see no point in Entity API especially if someone decides to use data classes instead of the interface. Using data classes I found no way of joining tables together

**Comment by vincentlauvlwj** [comment]
Entity based update API doesn't support where clauses, just use the DSL.
