### ISSUE TITLE
递归查询

### ISSUE THREAD

**Issue by Hell-Hope** [kotlin-orm/ktorm#311]
WITH cte([CategoryID],[CategoryName],[ParentID],[Level])
AS
(
    -- 查询语句
    SELECT [CategoryID],[CategoryName],[ParentID],1 AS [Level] FROM [dbo].[Category]
    WHERE [ParentID] IS NULL
    UNION ALL
    -- 递归语句
    SELECT c.[CategoryID],c.[CategoryName],c.[ParentID], cte.[Level] + 1
    FROM [dbo].[Category] c
    INNER JOIN cte
        ON c.[CategoryID] = cte.[ParentID]
)

SELECT [CategoryID],[CategoryName],[ParentID],[Level] FROM cte

Ktorm 怎么写

**Comment by vincentlauvlwj** [comment]
https://www.ktorm.org/zh-cn/dialects-and-native-sql.html#%E5%8E%9F%E7%94%9F-SQL
