### ISSUE TITLE
Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: org.jetbrains.kotlin.name.ClassId; nested exception is com.fasterxml.jackson.databind.JsonMappingException: org.jetbrains.kotlin.name.ClassId (through reference chain: com.example.duanlian.model.BaseEntity["data"]->java.util.ArrayList[0]->com.sun.proxy.$Proxy86["entityClass"])]

### ISSUE THREAD

**Issue by songjianzaina** [kotlin-orm/ktorm#318]
报错:Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: org.jetbrains.kotlin.name.ClassId; nested exception is com.fasterxml.jackson.databind.JsonMappingException: org.jetbrains.kotlin.name.ClassId (through reference chain: com.example.duanlian.model.BaseEntity["data"]->java.util.ArrayList[0]->com.sun.proxy.$Proxy86["entityClass"])]

**Comment by vincentlauvlwj** [comment]
需要在依赖里加上 ktorm-jackson 模块 https://www.ktorm.org/zh-cn/entities-and-column-binding.html#%E5%BA%8F%E5%88%97%E5%8C%96
