### ISSUE TITLE
unionAll自定义列如何使用？

### ISSUE THREAD

**Issue by ZhangHu1225** [kotlin-orm/ktorm#319]
SELECT iu.user_name, ia.user_id, ia.`type`, ia.`status`, 'user' as user
FROM idp_accounts ia
INNER JOIN idp_users iu ON ia.user_id = iu.user_id 
union all 
SELECT iad.user_name, ia.user_id, ia.`type`, ia.`status`, 'admin'  as user
FROM idp_accounts ia
INNER JOIN  idp_admins iad ON ia.user_id = iad.user_id   

比如上面这个sql， 为了区分 user还是admin，每个select后都加入了一个自定义列。

**Comment by vincentlauvlwj** [comment]
```kotlin
database
    .from(Accounts)
    .select(Accounts.userId, Accounts.userName, ArgumentExpression("user", VarcharSqlType).aliased("user"))
```

**Comment by HarveyZh0218** [comment]
好的 谢谢
