### ISSUE TITLE
Generic clause where

### ISSUE THREAD

**Issue by PetkevichPavel** [kotlin-orm/ktorm#322]
Hello, this `Issue` is more like a question for now, than improvement.

**Issue:**

I have to create a filter through DB with the 'where' clause, but not in the standard way such you are describing in your documentation, but in generic way:

here is an example of request:

```json
{
     "offset": 0,
     "limit": 44,
     "filter":[
	     {
		     "field":"state",
		     "value": "LEASED"
	     }
     ]
     ,
     "sort":[
	     {
		     "field": "id",
		     "order": "DESC"
     	     },
	     {
	     	     "field": "drivenDistance",
		     "order": "DESC"
	     }
     ]
}
```

With sort I already Found the way, and hoped that the filter will be pretty same but unfortunately not....

Here is how I'm trying to achieve this functionality:

My custom extension for creating and adding under `whereWithConditions` all filters as a BinaryExpressions:
```kotlin 
fun <E : Entity<E>> Table<E>.filterExpressions(
    sort: List<Filter.Body>,
    declaringColumn: MutableList<ColumnDeclaring<Boolean>>
) = declaringColumn.apply {
    sort.onEach { body ->
        this += BinaryExpression(
            body.operator.toDbOperatorType(),
            this@filterExpressions[body.field.toDbParamName()].asExpression(),
            DbTable[body.field.toDbParamName()].wrapArgument(body.value), // HERE IS THE ISSUE!!🤷🏽‍♂️  body.value -> is Any
            BooleanSqlType
        )
    }
}
//----------------------------------------------------------------------------------------
//Here is the place of usage:

db.from(DbTable).select()
     .orderBy(DbTable.sortExpressions(paginationRequest.sort))
     .whereWithConditions {
           DbTable.filterExpressions(paginationRequest.filter, it)
      }
      //......
```  

The main issue that I'm not be able to create Binary expression generically / or I did it but on the 90% and 10% I'm not be able to finish, here is the BinaryExpression example:

```kotlin
BinaryExpression(
       body.operator.toDbOperatorType(), // ✅
       this@filterExpressions[body.field.toDbParamName()].asExpression(), // ✅
       DbTable[body.field.toDbParamName()].wrapArgument(body.value.toString()), // ❌
       BooleanSqlType 
)
``` 
When I'm trying to wrap argument on the right: ScalarExpression<*>:
```kotlin
 DbTable[body.field.toDbParamName()].wrapArgument(body.value.toString())
``` 
This is will not work because the `wrapArgument` is waiting on `T` which I don't have at this moment when I'm using `DbTable[nameColumn]` / `DbTable.get(nameColumn)`

In case you are able to help me, I'm opening for any ideas / maybe someone from the community already solved some of that type of issue.

Thanks in advance.

**Comment by vincentlauvlwj** [comment]
Try this: 

```kotlin
val column = DbTable[body.field.toDbParamName()] as Column<Any>
val value = body.value as Any?
column.wrapArgument(value)
```

**Comment by PetkevichPavel** [comment]
@vincentlauvlwj Thank you for your response I adjusted code, but unfortunately: 

**
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Enum (java.lang.String and java.lang.Enum are in module java.base of loader 'bootstrap')
**

PS> it works on the primitives, but on ENUMS....

Here is updated function:
```kotlin
fun <E : Entity<E>> Table<E>.filterExpressions(
    sort: List<Filter.Body>,
    declaringColumn: MutableList<ColumnDeclaring<Boolean>>
) = declaringColumn.apply {
    sort.onEach { body ->
        (DbBooking.DbTable[body.field.toDbParamName()] as? Column<Any>)?.let {
            this += BinaryExpression(
                body.operator.toDbOperatorType(),
                this@filterExpressions[body.field.toDbParamName()].asExpression(),
                it.wrapArgument(body.value),
                BooleanSqlType
            )
        }
    }
}
```

**Comment by PetkevichPavel** [comment]
Hello @vincentlauvlwj , currently I found temporary solution, here is it:

```kotlin
inline fun <reified T : Enum<T>> List<Filter.Body>.enum(fieldName: String) = mapNotNull { body ->
   body.takeIf { it.field == fieldName }?.run {
       copy(value = enumValueOf<T>(body.value.toString()))
   }
}
```

This ext.function is searching via `field` what has to be presented as enum and replace the `value: Any` with enum `value: Enum<T>`, in that case everything is works pretty good, but personally I do not think that this is a final solution, and I will be back to this issue later, unfortunately currently I do not have time and I have to move forward, but If you will find/already know something what can be better / already exist in lib I will be more than appreciate to hear it from you 😃

Btw, here is the place of call after quickFix:
```kotlin
whereWithConditions {
   filterExpressions(it, paginationRequest.filter?.enum<Booking.State>(state.name))
}
```
