### ISSUE TITLE
springmvc mybatis ktorm java/kotlin混合开发报java.lang.NoClassDefFoundError: Could not initialize class com.xx.xx.ktorm.XXTasks

### ISSUE THREAD

**Issue by zhangwei911** [kotlin-orm/ktorm#330]

**Comment by vincentlauvlwj** [comment]
不是 Ktorm 的问题，检查一下你自己的代码

**Comment by zhangwei911** [comment]
`
object XXTasks : Table<EaipTask>("l_task") {
  val id = varchar("id").primaryKey().bindTo { it.id }
  val uniqueid = varchar("uniqueid").bindTo { it.uniqueid }
  val data = varchar("data").bindTo { it.data }
  val path = varchar("path").bindTo { it.path }
  val type = varchar("type").bindTo { it.type }
  val createtime = jdbcTimestamp("createtime").bindTo { it.createtime }
  val result = varchar("result").bindTo { it.result }
  val trycount = int("trycount").bindTo { it.trycount }
  val iscomplete = varchar("iscomplete").bindTo { it.iscomplete }
  val lastexecutetime = jdbcTimestamp("lastexecutetime").bindTo { it.lastexecutetime }
  val executetime = jdbcTimestamp("executetime").bindTo { it.executetime }
}
`

找着示例写的,这个无法初始化
jdbcTimestamp,timestamp都试过,不行
