### ISSUE TITLE
能否根据查询条件来决定是否拼接where条件?

### ISSUE THREAD

**Issue by DroidEye2ONGU** [kotlin-orm/ktorm#334]
例如一张表 table有字段 a int,b varchar(100)
根据目前探索,在拼接条件时,若想以这两个字段为条件查询,必须传入非null的值进行条件拼接,这样对于接口选传参数时,业务中将会存在大量的空判断和sequence拼接

**Comment by vincentlauvlwj** [comment]
举个例子说明一下？

**Comment by vincentlauvlwj** [comment]
参考 #118

**Comment by DroidEye2ONGU** [comment]
> 参考 #118

非常感谢!
