### ISSUE TITLE
ResultSet.getArray(index) return PGobject in custom SqlType

### ISSUE THREAD

**Issue by tox1cozZ** [kotlin-orm/ktorm#335]
I want to create a custom postgresql type for a citext[] column. But when I call getArray, I get PGobject instead of Object[] with PGobject elements. When using a native connection, there are no such problems. I suspect that this is because of CachedRowSet the postgres driver cannot get the array type.
![Screenshot_8](https://user-images.githubusercontent.com/7694196/135759031-106af35a-a032-4960-a077-9a81289c5628.jpg)

**Comment by tox1cozZ** [comment]
@vincentlauvlwj Hi. Will this be fixed?

**Comment by vincentlauvlwj** [comment]
Is there any problem to return a `PBobject`?

**Comment by tox1cozZ** [comment]
Yes. It cannot be turned into an array correctly. Postgres doesn't have a public method for converting, which is non-trivial.
