### ISSUE TITLE
请问实体Api的列绑定列子中，可以将同一部门的员工绑定到Department类中进行查询吗？

### ISSUE THREAD

**Issue by luckykelan** [kotlin-orm/ktorm#340]
可以实现在Department新加一个属性，通过绑定同一个departmentId的多个Employees，在查询某个Department时候，连带把这个部门的所有员工查询出来吗？

**Comment by vincentlauvlwj** [comment]
参考这个 https://github.com/kotlin-orm/ktorm/issues/283

**Comment by luckykelan** [comment]
这个issue，想获取到这个字段需要额外通过方法调用，有没有办法可以像引用绑定这种方式，在` database.departmentId.toList()`直接能获取到employees?

**Comment by vincentlauvlwj** [comment]
直接获取容易导致 n+1 问题，不推荐

**Comment by luckykelan** [comment]
在#283 通过额外的方法获取属性，在方法里直接使用了db.employees，这么使用是不是意味着所有Database的扩展属性都要写在顶层里？
如果这样的话，在多人开发的时候太难维护了吧

**Comment by luckykelan** [comment]
参数需要传入db，就只能在注入了Database的文件里调用，限制太多了

**Comment by vincentlauvlwj** [comment]
代码好不好维护主要看你怎么写，`loadEmployees` 函数不一定非要是成员函数，它也可以是扩展函数，甚至可以是别的类里面的成员扩展函数

**Comment by luckykelan** [comment]
和loadEmployees函数放在哪没关系，它的实现用到了db.employees，那是不是val Database.employees get() = this.sequenceOf(EmployeesDao) 需要是全局的，或者在这个实体类也写一遍？

**Comment by luckykelan** [comment]
它的入参需要db，就要求调用处需要有注入的Database

**Comment by luckykelan** [comment]
如果loadEmployees 是扩展函数，就只能是在有 val Database.employeesget() = this.sequenceOf(EmployeesDao) 这行代码的地方，也就是service，现在不是我怎么写的问题，是你这个框架只能要求我这么写

**Comment by vincentlauvlwj** [comment]
框架并没有要求你把 `db.employees` 定义成全局属性，甚至也没有要求一定要有这个属性。

至于你说的在 `loadEmployees` 里面用不了的问题，你有两个方案：

1. 直接用 `sequenceOf` 代替，比如 

```kotlin
fun loadEmployees(db: Database) = db.sequenceOf(Employees).filter { it.departmentId eq id }.toList()
```

2. 既然你的 `db.employees` 不是全局的，那它肯定包含在一个类的作用域里吧，那么为什么不把 `loadEmployees` 也放在那个作用域类里作为一个扩展函数呢，比如

```kotlin
object DbScope {
    val Database.employees get() = this.sequenceOf(Employees)

    fun Department.loadEmployees(db: Database) = db.employees.filter { it.departmentId eq id }.toList()
}
```

所以说，代码好不好维护，主要还是看怎么写，哪里来的那么多限制...

**Comment by vincentlauvlwj** [comment]
甚至还有第三种，假设你把 `db.employees` 定义在了一个作用域类里面，比如：

```kotlin
object DbScope {
    val Database.employees get() = this.sequenceOf(Employees)
}
```

那么我们只需要在 `loadEmployees` 里面使用 `with` 函数，就可以访问到它：

```kotlin
fun loadEmployees(db: Database): List<Employee> {
    with(DbScope) {
        return db.sequenceOf(Employees).filter { it.departmentId eq id }.toList()
    }
}
```
