### ISSUE TITLE
EntitySequence我没找到怎么支持动态SQL的方式，特向你请教一下

### ISSUE THREAD

**Issue by kamjin1996** [kotlin-orm/ktorm#341]
代码：
this.database.employees.find{
             it.name eq request.name!!
        }
上面代码我必须添加!!才能查询，但是这个name参数是可选的，也就是空的情况下这个代码会抛错，我想让name参数不存在的情况下当前条件不生效，换句话说就是用EntitySequence方式的话，该怎么写动态SQL？

**Comment by vincentlauvlwj** [comment]
用 if 语句：

```kotlin
if (request.name != null) {
    database.employees.find { it.name eq request.name }
}
```

**Comment by kamjin1996** [comment]
可是这样的话，我多个条件情况下，怎么动态sql呢？不会要这样写把：伪代码
var employees = null
if (request.name != null) {
  employees =  database.employees.find { it.name eq request.name }
}

if (request.superAdmin!= null) {
 employees =   database.employees.find { it.super_admin eq request.superAdmin}
}

if(request.age != null && request.age>0 ){
 employees =   database.employees.find { it.age le request.age}
}

并且需求是这些条件中，哪个参数不为空，就拼接哪个参数作为条件
，就算if改成when 也不优雅把 也没法达到我想要的效果

**Comment by vincentlauvlwj** [comment]
参考这个 https://github.com/kotlin-orm/ktorm/issues/118

**Comment by kamjin1996** [comment]
> 用 if 语句：
> 
> ```kotlin
> if (request.name != null) {
>     database.employees.find { it.name eq request.name }
> }
> ```

我用过mybatisplus，它里面的支持是这样的：
this.ktQuery().eq(request.superAdmin != null , Employee::superAdmin , request.superAdmin ).list()
eq方法第一个参数是condition，为false时当前eq语句不拼接到sql，本质就是一个拼接时的if判断包装，利用kt的强大dsl构建能力，肯定是可以胜任只是写法方式需要斟酌一二把，
那我在想这个EntitySequence，使用效果可能可以这样:
this.database.employees.find{
  conditionCase {
   request.superAdmin !=null ->  it.superAdmin eq request.superAdmin
   request.name != null ->  it.name eq  request.name
  }
}

可能复杂了 但就是这个意思，动态条件sql在任何查询中都很常用，而且用EntitySequence挺舒服的，希望能支持一下

**Comment by kamjin1996** [comment]
> 参考这个 #118

感觉还可以，但还是感觉不够简练优雅，语句后面那两个!!号 也很难受了╮(╯▽╰)╭

**Comment by vincentlauvlwj** [comment]
```kotlin
this.database.employees.find{
    conditionCase {
        request.superAdmin !=null -> it.superAdmin eq request.superAdmin
        request.name != null -> it.name eq request.name
    }
}
```

你觉得这样写跟直接用 when 语句有区别吗.....

```kotlin
this.database.employees.find{
    when {
        request.superAdmin !=null -> it.superAdmin eq request.superAdmin
        request.name != null -> it.name eq request.name
    }
}
```

**Comment by kamjin1996** [comment]
可是支持写when吗？这个find作用域里

**Comment by vincentlauvlwj** [comment]
> 可是支持写when吗？这个find作用域里

支持，你喜欢写 if 还是 when 都可以

**Comment by kamjin1996** [comment]
可以的
我测下看是不是想要的效果 ，感谢解答

**Comment by kamjin1996** [comment]
this.database.employees.find {
            when {
                request.superAdmin != null -> it.super_admin eq request.superAdmin!!
                request.name != null -> it.name eq request.name!!
                else ->  it.name eq request.name!!
            }
        }

这个else，必须要写一个返回值，但不知道该返回个啥

**Comment by vincentlauvlwj** [comment]
不知道返回什么，就返回 `ArgumentExpression(true, BooleanSqlType)`

**Comment by kamjin1996** [comment]
那基本就是空对象模式解决一下咯，行吧就这样把 能用就行。。。。

**Comment by kamjin1996** [comment]
service代码：

this.database.employees.filter {
            when {
                request.superAdmin != null -> it.super_admin eq request.superAdmin!!
                request.name != null -> it.name eq request.name!!
                else -> ArgumentExpression(true, BooleanSqlType)
            }
        }.toList()
        
        我试了，这不是动态sql拼接，感觉很无奈
   
请求url：
http://localhost:8080/employee/list?superAdmin=false&name=ADMIN

json查询结果：
{
"code": 200,
"msg": "success",
"data": {
"items": [
{
"name": "查理",
"id": 2,
"superAdmin": false
}
]
}
}
        
     
sql日志:

2021-11-09 11:39:35.541 DEBUG 10504 --- [nio-8080-exec-1] org.ktorm.database                       : SQL: select employee.id as employee_id, employee.name as employee_name, employee.account as employee_account, employee.password as employee_password, employee.super_admin as employee_super_admin, employee.create_time as employee_create_time, employee.update_time as employee_update_time from employee where employee.super_admin = ? 
2021-11-09 11:39:35.541 DEBUG 10504 --- [nio-8080-exec-1] org.ktorm.database                       : Parameters: [false(boolean)]
2021-11-09 11:39:35.564 DEBUG 10504 --- [nio-8080-exec-1] org.ktorm.database                       : Results: 1

**Comment by kamjin1996** [comment]
在object Employee中创建方法：
inline fun <E : Any, T : BaseTable<E>> EntitySequence<E, T>.filterIf(
        condition: Boolean,
        predicate: (T) -> ColumnDeclaring<Boolean>
    ): EntitySequence<E, T> {
        if (condition) {
            return this.filter(predicate)
        } else {
            return this
        }
    }

这样使用：

this.database.employees
            .filterIf(request.name != null) {
                it.name eq request.name!!
            }.filterIf(request.superAdmin != null) {
                it.super_admin eq request.superAdmin!!
            }
            .toList().map {
                OpenEmployeeListResponse.Item(it.name, it.id, it.super_admin)
            }.let { OpenEmployeeListResponse(it) }
可以达到想要的效果
但总感觉 != null和这些if和{ }太java了，用法不太精炼，希望能出个api优化一下EntitySequence中动态SQL的用法

**Comment by vincentlauvlwj** [comment]
以 Kotlin 强大的扩展性，我们根本不需要在框架中提供这种 API，如果你喜欢 mybatis plus 的那种写法，自己写一个就可以了

```kotlin
fun <E : Any, T : BaseTable<E>, C : Any>
EntitySequence<E, T>.eq(condition: Boolean, column: Column<C>, value: C?): EntitySequence<E, T> {
    if (condition) {
        return this.filter { column eq value!! }
    } else {
        return this
    }
}
```

用起来是这样的：

```kotlin
database.employees
    .eq(request.name != null, Employees.name, request.name)
    .eq(request.superAdmin != null, Employees.superAdmin, request.superAdmin)
```

如果你喜欢，你可以把这段代码复制到你的项目里，但是 Ktorm 框架不会提供，每个人都有自己的想法，Ktorm 只需要提供最核心的能力就可以了，那些边缘的扩展完全可以用户自己来实现
