### ISSUE TITLE
当主键类型为java.util.UUID时候，调用EntitySequence.add方法后，报错The value of non-null property  doesn't exist

### ISSUE THREAD

**Issue by luckykelan** [kotlin-orm/ktorm#344]
![image](https://user-images.githubusercontent.com/37082159/141040038-45abcd5c-b9ba-48ab-902a-cfba66531251.png)

![image](https://user-images.githubusercontent.com/37082159/141040018-ed05e6dc-8704-4376-bdec-7084d12afcb8.png)

报错信息：
![image](https://user-images.githubusercontent.com/37082159/141039965-68e1d873-cce6-4ed8-8d5b-331fbcf70b8a.png)

**Comment by vincentlauvlwj** [comment]
为什么不设置主键的值？

**Comment by luckykelan** [comment]
是插入，id是自增的，如果设置了id就乱了

**Comment by vincentlauvlwj** [comment]
uuid 怎么自增，自增的主键应该是个数字吧

**Comment by luckykelan** [comment]
mysql8的一个函数，
![image](https://user-images.githubusercontent.com/37082159/141040646-62018f77-383f-4a03-b90e-305d16f51384.png)

**Comment by vincentlauvlwj** [comment]
看看表对象的定义

**Comment by luckykelan** [comment]
```
CREATE TABLE `file` (
  `id` binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  `url` VARCHAR(255) NOT NULL, 
  `size` VARCHAR(50) NOT NULL, 
	`main_color` VARCHAR(10) , 
	`file_name` VARCHAR(50)
)
```

**Comment by luckykelan** [comment]
``` kotlin
object FileDao : Table<File>("file"){
	var id = uuid("id").primaryKey().bindTo { it.id }
	var url = varchar("url").bindTo { it.url }
	var size = varchar("size").bindTo { it.size }
	var mainColor = varchar("main_color").bindTo { it.mainColor }
	var fileName = varchar("file_name").bindTo { it.fileName }
}
```

**Comment by vincentlauvlwj** [comment]
> ```
> CREATE TABLE `file` (
>   `id` binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
>   `url` VARCHAR(255) NOT NULL, 
>   `size` VARCHAR(50) NOT NULL, 
> 	`main_color` VARCHAR(10) , 
> 	`file_name` VARCHAR(50)
> )
> ```

建表的时候没有把 id 字段设置成主键，在 mysql 看来，这只是一个普通的无主键的表

**Comment by luckykelan** [comment]
额，是主键的，建表后我设置的
![image](https://user-images.githubusercontent.com/37082159/141042130-31ea1152-8114-4211-a746-bb7402dc49cb.png)

**Comment by luckykelan** [comment]
请问有解决办法吗？

**Comment by vincentlauvlwj** [comment]
这个是 MySQL 的问题，MySQL 只支持返回数字自增的主键的值，uuid 是不支持的，你有两个解决方法：

- 改用数字自增主键 `id bigint unsigned not null auto_increment`
- 调用 `add` 方法之前自己设置主键的值
