### ISSUE TITLE
请教当实体类有引用绑定时的插入问题

### ISSUE THREAD

**Issue by luckykelan** [kotlin-orm/ktorm#345]
例子中Employee通过引用绑定持有一个Department对象，如果调用database.employee.add(employee)插入一条数据时，需要根据department_id构造一个Department为employee对象赋值后才能插入吗

**Comment by vincentlauvlwj** [comment]
是的

**Comment by luckykelan** [comment]
这是使用引用绑定的副作用吗？department_id是已知的，但每次插入还都要走一遍多余的查询

**Comment by vincentlauvlwj** [comment]
也可以不查询，创建一个空的 `Department` 对象也可以，里面只包含 id

```kotlin
department = Department { id = 123 }
```
