### ISSUE TITLE
引用绑定查询时，left join字段只能是主键吗？

### ISSUE THREAD

**Issue by luckykelan** [kotlin-orm/ktorm#346]
存储的是另一张表的code，非主键id，可以在查询是指定left join的字段吗？

**Comment by vincentlauvlwj** [comment]
必须在 Ktorm 里面使用 `primaryKey()` 函数指定关联的字段为主键，实际上你的表是不是主键没有关系

**Comment by luckykelan** [comment]
表中存在一个唯一标识code和一个自增主键id，如果所有关联关系都指向的是code，那么在Ktorm里，用 primaryKey()指定code也可以对吗， primaryKey()和表中的主键可以不是一个

**Comment by vincentlauvlwj** [comment]
可以

**Comment by luckykelan** [comment]
感谢
