### ISSUE TITLE
Select COUNT doesn't work as should.

### ISSUE THREAD

**Issue by PetkevichPavel** [kotlin-orm/ktorm#347]
Hello, on my project I faced with the issue with count under select. The result after the using it is not proper and I'm a bit confused how to proceed with that. Here is my code:

```kotlin
val size = db.from(this).select(count(id)).applyFilters().totalRecords
```
applyFilters - is my custom function which is applying filter on select.

the result is not correct and I see the error in SQL query which is pregenerated by KTORM:

`DEBUG org.ktorm.database - SQL: select count(*) from (select count(booking.id) from booking where (booking.state = ?) and (booking.user_id = ?)) tmp_count` instead of : `select count(booking.id) from booking where (booking.state = ?) and (booking.user_id = ?))` and because od the wrong query the result is wrong.

**Comment by vincentlauvlwj** [comment]
Because you are using `totalRecords` incorrectly. This property returns the total record count for the query. 

Assuming there are 10 records matching the filters in your table and you have a query like this: 

```kotlin
val query = db.from(this).select().applyFilters()
```

Using `query.totalRecords` will return 10 because this query have 10 results.

**Comment by vincentlauvlwj** [comment]
But if your query is like this: 

```kotlin
val query = db.from(this).select(count(id)).applyFilters()
```

Using `query.totalRecords` will always return 1, because there is only 1 record in the query result, and the record is a number 5.  This is why you see the generated SQL is `select count(*) from (select count(booking.id) from booking where (booking.state = ?) and (booking.user_id = ?)) tmp_count`

**Comment by vincentlauvlwj** [comment]
I think I have made it clear in the documentation: https://www.ktorm.org/api-docs/org.ktorm.dsl/-query/total-records.html

**Comment by PetkevichPavel** [comment]
Sorry for the late answer , you were right, I already fixed it with the following extension function:

```kotlin

/**
 * QuerySource extension function in order to take count of records with select(count[column]).
 * @param column - ColumnDeclaring.
 * @param query - apply some query: filters for instance.
 */
fun QuerySource.getCountWithQuery(column: ColumnDeclaring<*>, query: Query.() -> Query) =
    select(column).groupBy(column).query().mapNotNull {
        it.size()
    }.firstOrNull().orZero()
```
