### ISSUE TITLE
Custom select column

### ISSUE THREAD

**Issue by PedroD** [kotlin-orm/ktorm#353]
Hello,

how can I request for a custom select column? I am looking for something like this:

```kotlin
val fullCount = toExpression("count(*) OVER()").aliased("full_count")

db
   .from(MyTable)
   .select(MyTable).col1, MyTable).col2, fullCount )
   (...)
```

Is this possible? I hope so, because the only alternative solution I've found is to build the full query as string, and this beats the point of Ktorm.

**Comment by vincentlauvlwj** [comment]
I don't think we should allow passing SQL segments to the framework, it might lead to SQL injections risks.
