### ISSUE TITLE
Support for composite keys

### ISSUE THREAD

**Issue by ssoper** [kotlin-orm/ktorm#358]
Apologies if this functionality exists but I couldn’t find anything that matched this in the documentation.

Imagine you have two tables + lookup table.

```
Tickers
id: int
name: String

Tags
id: int
name: String

TickerTags
ticker_id: int -> fk to Tickers.id
tag_id: int -> fk to Tags.id
```

If I wanted to delete a specific TickerTag row I'd need I’d something like the following
```kotlin
database.delete(TickerTags) { it.ticker_id eq tickerId and it.tag_id eq tagId }
```

Every example I see shows only the use of a single condition predicate nor can I find support in the code for this.

**Comment by vincentlauvlwj** [comment]
Of course you can have a complex condition for `delete` function. It's supported.

**Comment by ssoper** [comment]
Glad to hear it, do you happen to have an example?

**Comment by ssoper** [comment]
Ok looks like if I wrap with some parentheses it could work

```kotlin
database.delete(TickerTags) { (it.ticker_id eq tickerId).and(it.tag_id eq tagId) }
```

Might be a good addition to your documentation.
