### ISSUE TITLE
Ktorm怎么实现手动指定使用某个mysql索引 如mysql的语法是 use INDEX (idx_xxxx)

### ISSUE THREAD

**Issue by DreamYa0** [kotlin-orm/ktorm#361]
Ktorm怎么实现手动指定使用某个mysql索引 如mysql的语法是 use INDEX (idx_xxxx)

**Comment by vincentlauvlwj** [comment]
参考这篇文章，任何特殊的语法都可以通过类似的方法来扩展 https://www.liuwj.me/posts/ktorm-dialect-extension/
