### ISSUE TITLE
Ability to create own AggregateExpression?

### ISSUE THREAD

**Issue by KocproZ** [kotlin-orm/ktorm#362]
Is there a way to create own AggregateExpression? I'm using postgresql and wanted to implement a STRING_AGG  function, but I got stuck. Looks like all the predefined expressions use the AggregateType enum, and I haven't found a way to get around that.

**Comment by vincentlauvlwj** [comment]
Just ignore the enum, simply creating a `StringAggExpressionn` is OK.

**Comment by daharon** [comment]
I have a project which has several user-defined aggregate functions in PostgreSQL.
Here is an example of what I did.

The function is defined like so:
```plpgsql
CREATE OR REPLACE AGGREGATE EMA(col NUMERIC, periods INTEGER)
    (SFUNC = _ema_sfunc, STYPE = _ema_stype, FINALFUNC = _ema_ffunc);
COMMENT ON AGGREGATE EMA(NUMERIC, INTEGER) IS 'Exponential moving average - EMA(<column>, <periods>).';
```

I use it from Ktorm `select` expressions like this:
```kotlin
/**
 * _Exponential Moving Average_ technical indicator.
 *
 * A user-defined aggregate function translated to `ema(price, periods)` in SQL.
 */
fun <C : Number> ema(price: ColumnDeclaring<C>, periods: Int): FunctionExpression<C> =
    FunctionExpression(
        functionName = "ema",
        arguments = listOf(price.asExpression(), ArgumentExpression(periods, IntSqlType)),
        sqlType = price.sqlType,
    )
```

**Comment by KocproZ** [comment]
This approach is even easier than what I was trying, Thanks for the help!
