### ISSUE TITLE
使用ksp让ktorm更好的支持data class、减少样板代码

### ISSUE THREAD

**Issue by lookup-cat** [kotlin-orm/ktorm#373]
ksp是类似于kapt的自动代码生成工具 拥有更好的性能[https://kotlinlang.org/docs/ksp-why-ksp.html#comparison-to-kapt](https://kotlinlang.org/docs/ksp-why-ksp.html#comparison-to-kapt)

目前ktorm 使用data class存在的问题 可以通过ksp得到改善

> 无法使用列绑定功能：由于直接以 BaseTable 作为父类，我们无法在定义表对象时使用 bindTo、references 等函数指定数据库列与实体类属性的绑定关系，因此每个表对象都必须实现 doCreateEntity 函数，在此函数中手动创建实体对象，并一一对各个属性赋值。
无法使用实体对象的增删改 

可以利用ksp自动生成Table类并实现doCreateEntity方法

> API：由于使用 data class 作为实体类，Ktorm 无法对其进行代理，因此无法检测到实体对象的状态变化，这导致 sequence.add(..)、entity.flushChanges() 等针对实体对象的增删改 API 将无法使用。但是 SQL DSL 并没有影响，我们仍然可以使用 database.insert(..) {..}、database.update(..) {..} 等 DSL 函数进行增删改操作。

通过ksp自动生成代码+扩展方法方式实现sequence.add(..) database.insert(..) {..}  以及 database.update(..) {..}（这需要实体类必须绑定至少一个主键) 

除了更好的支持data class之外，自动生成Table还可以减少很多样板代码，并且通过扩展方法还能自动生成批量插入、更新的方法，例如个人项目中是这样实现的：
![截屏2022-02-22 下午6 10 54](https://user-images.githubusercontent.com/45026715/155110686-4a8913b6-f154-4ee8-b078-ca4d225c335d.png)

大佬如果觉得可行，我会试着实现这个方案并提交PR

**Comment by vincentlauvlwj** [comment]
这个方案当然可行，但是我认为不应该提 PR 而是建一个新的代码库。我希望 ktorm 项目本体只包含它的核心代码，其他各种扩展应该放在独立的代码仓库里

就像之前曾经为了尝试 kapt，我们开了一个 ktorm-kapt 项目（虽然因为时间关系还没有正式开工），现在我们也可以建一个 ktorm-ksp 项目

代码库我已经建好了，也给你发送了 member 邀请，如果你有兴趣，可以直接在这个仓库上提交代码 https://github.com/kotlin-orm/ktorm-ksp

**Comment by lookup-cat** [comment]
谢谢大佬 我会抽空来实现它

**Comment by lookup-cat** [comment]
> 这个方案当然可行，但是我认为不应该提 PR 而是建一个新的代码库。我希望 ktorm 项目本体只包含它的核心代码，其他各种扩展应该放在独立的代码仓库里
> 
> 就像之前曾经为了尝试 kapt，我们开了一个 ktorm-kapt 项目（虽然因为时间关系还没有正式开工），现在我们也可以建一个 ktorm-ksp 项目
> 
> 代码库我已经建好了，也给你发送了 member 邀请，如果你有兴趣，可以直接在这个仓库上提交代码 https://github.com/kotlin-orm/ktorm-ksp

可以帮我添加下提交代码的权限吗？

**Comment by vincentlauvlwj** [comment]
@lookup-cat 好了
