### ISSUE TITLE
Does it support asynchronous and coroutines?

### ISSUE THREAD

**Issue by gtfhxy** [kotlin-orm/ktorm#375]
Ktorm can run with Ktor, but it doesn't seem to be fully compatible because Ktor is based on asynchronous and coroutines. Are there any plans for asynchronous and coroutines support in the near future?

**Comment by LeeWlving** [comment]
https://github.com/kotlin-orm/ktorm-r2dbc,please check this.

**Comment by gtfhxy** [comment]
> https://github.com/kotlin-orm/ktorm-r2dbc, please check this.

Those codes don't look like they're continuing to be updated.

**Comment by vincentlauvlwj** [comment]
Yes, I have a plan, but not in the near future.
