### ISSUE TITLE
下一个版本计划什么时候？

### ISSUE THREAD

**Issue by shenlq1017** [kotlin-orm/ktorm#378]
现在一直使用java的orm框架，一直想转kotlin的。本项目感觉挺符合预期的，但是看到代码已经将近一年没有维护升级了，请问后面还需继续升级吗？下个版本的计划是什么时候？

**Comment by Anivie** [comment]
前几天有人问作者说是沉迷原神一直没更，这段时间准备要更新了

**Comment by Anivie** [comment]
听说作者最近准备更新了，不知道是不是真的

**Comment by vincentlauvlwj** [comment]
是真的，沉迷原神也是真的😂

**Comment by lookup-cat** [comment]
> 是真的，沉迷原神也是真的😂

原来你也玩原神😄

**Comment by liukeshao** [comment]
> 是真的，沉迷原神也是真的😂

要不我给你代练原神，你更新吧😂，升级下kt版本也行

**Comment by csc365kl** [comment]
我们轮流给你代练吧

**Comment by onXoot** [comment]
哈哈哈 这个issue 终于可以关了
