### ISSUE TITLE
isEmpty/isNotEmpty suboptimal performance

### ISSUE THREAD

**Issue by hallundbaek** [kotlin-orm/ktorm#380]
The implementation of `isEmpty` and `isNotEmpty` for `EntitySequence` is not performant as it relies on `count()`.

My own, small and limited tests, suggest that using `firstOrNull() == null` and `firstOrNull() != null` seem to be more performant.

**Comment by vincentlauvlwj** [comment]
For MySQL or PostgreSQL this would be a good approach, but for other databases (eg. Oracle) it might not.
