### ISSUE TITLE
The entity is not attached to any database yet

### ISSUE THREAD

**Issue by eddy-gao** [kotlin-orm/ktorm#381]
使用class做实体类的时候，entity.flushChanges报错:The entity is not attached to any database yet。版本号:3.4.1

**Comment by vincentlauvlwj** [comment]
看详细代码

**Comment by eddy-gao** [comment]
![选区_034](https://user-images.githubusercontent.com/53897990/160976347-94b3bc46-aec8-4e01-bc07-1940f1ba998f.png)
![选区_035](https://user-images.githubusercontent.com/53897990/160976352-cce45487-3bca-430f-969a-9cb093920668.png)
![选区_036](https://user-images.githubusercontent.com/53897990/160976358-56dd6f68-492c-4eba-8718-06897f9f4f9d.png)

**Comment by vincentlauvlwj** [comment]
既然你说你用 class 作为实体类，那么代码里面的 `interface User : Entity<User>` 是什么

**Comment by eddy-gao** [comment]
表达错了，因为我需要用到别名，所以根据文档用class做了dao，这种情况下实体是需要从interface也改为class么？

**Comment by vincentlauvlwj** [comment]
> 表达错了，因为我需要用到别名，所以根据文档用class做了dao，这种情况下实体是需要从interface也改为class么？

这是当然，你都还是 interface，怎么能说用 class 做实体类呢
