### ISSUE TITLE
使用kotlin dsl查询时，当确定查询结果只有一条时，应该怎么获取数据？

### ISSUE THREAD

**Issue by luckykelan** [kotlin-orm/ktorm#382]
比如我有一个这样的查询：
```
database.from(UserDao).select().where{ UserDao.id eq param.id }
```
结果集之可能有一条或者零条，当我判断有一条时，我应该怎么获取User的数据，请问有比迭代获取更好的方式吗？

**Comment by vincentlauvlwj** [comment]
```kotlin
val user = query.map { row -> Users.createEntity(row) }.firstOrNull()
```

**Comment by luckykelan** [comment]
非常感谢，我想给QueryRowSet提供一个扩展方法toMap，可以写成这样
```
val user = query.map{ row -> row.toMap() }.firstOrNull()
```
但是看了QueryRowSet的源码没太看明白应该怎么写....，请问可以请教一下吗？

**Comment by vincentlauvlwj** [comment]
`toMap` 方法的目的是要干什么

**Comment by luckykelan** [comment]
因为实际场景，这条语句会有left join，select方法会指定查询某几列，在map里不能直接使用类似Users.createEntity(row)的这种方法。

**Comment by luckykelan** [comment]
所以想把row转成一个map；
但是感觉Query有些奇怪，它可以遍历，但是不能使用常规的firstOrNull或者通过下标获取值，我现在的做法是
```
fun Query.firstOrNull(): QueryRowSet? {
    if (totalRecords != 0) {
        this.forEachIndexed { index, row ->
            if (index == 0) {
                return row
            }
        }
    }
    return null
}
```
给Query加了个fisrtOrNull扩展函数，不知道合不合理

**Comment by vincentlauvlwj** [comment]
不合理

**Comment by vincentlauvlwj** [comment]
Query 的设计就是只能单向遍历并且只能遍历一次，在遍历的过程中把数据取出来并做相应的转换

**Comment by luckykelan** [comment]
> 单向遍历并且只能遍历一次，在遍历的过程中把数据取出来并做相应的转换

我没太理解，firstOrNull()好像没有违背这个设计；
如果不这样的话，好像我提的这个需求没有很好的处理方式

**Comment by vincentlauvlwj** [comment]
你以为你返回的 `QueryRowSet` 只有一行数据，但它实现了 JDBC 的 `ResultSEt`，实际上是整个查询结果的容器，想象一下我通过你的 `firstOrNull` 拿到一个 `QueryRowSet`，然后调用它的 `next` 方法会怎么样？

```kotlin
val rowSet = query.firstOrNull()

while (rowSet.next()) {
    println(rowSet.getString(1))
}
```

**Comment by vincentlauvlwj** [comment]
> 在遍历的过程中把数据取出来并做相应的转换

这句话的意思是，你必须在遍历的过程中取数据并转换成你要的结果，而不是先遍历返回 `QueryRowSet` 再转换。你的 `firstOrNull` 里面已经遍历过一次了

**Comment by vincentlauvlwj** [comment]
是的

**Comment by luckykelan** [comment]
非常感谢！
