### ISSUE TITLE
KTORM without a Schema

### ISSUE THREAD

**Issue by BubbaJoe** [kotlin-orm/ktorm#384]
Hello,

KTORM looks really nice. I was wondering if it was possible use KTORM for SELECT queries without defining schema, so basically just provide the tables names and fields. I want to run simple queries (read-only queries) across different databases in different dialects.

For example, something like this: which uses meta wrappers.
https://www.jooq.org/doc/3.16/manual/getting-started/use-cases/jooq-as-a-sql-builder-without-codegeneration/
PS: JOOq doesn't seem to support Oracle (unless you get the commercial license) which is why im looking for alternatives.

**Comment by vincentlauvlwj** [comment]
Emmm... I don't think it's a good idea. It is not type safety and error-prone.

**Comment by BubbaJoe** [comment]
Yes, it's not type-safe. And yes, there will need to be specific error handling logic.

**Comment by vincentlauvlwj** [comment]
no such plan
