### ISSUE TITLE
Usage of LIKE operator in PostgreSQL

### ISSUE THREAD

**Issue by d35h** [kotlin-orm/ktorm#392]
Hello,

I checked issues here in the repo and I didn't find anything related to the one have, so here it is :)

When I try to execute `LIKE` operation against `PostgreSQL` using `ktorm`, I'm getting the following:
`ERROR: operator does not exist: integer ~~ character varying`

It happens because `ktorm` generates the query as follows:
`select * from my_table where my_id like '3';`

However, the correct one would be:
`select * from my_table where my_id::text like '3';`

My code is
```
BinaryExpression(
        BinaryExpressionType.LIKE,
        ColumnExpression(myTable, "my_id", VarcharSqlType),
        ArgumentExpression(body.value.toString(), VarcharSqlType),
        BooleanSqlType
)
```

My question would be is there a way how to tell/force `ktorm` to cast `my_id` to `text` when rendering the query?

Thanks,
Dani

**Comment by vincentlauvlwj** [comment]
Close this issue because there is already a simillar one #146
