### ISSUE TITLE
case when ... then ... end

### ISSUE THREAD

**Issue by 2x2xplz** [kotlin-orm/ktorm#394]
I've read most of the docs and searched, but don't see any examples or support for a SQL `case when` expression. Is this supported via some keyword, or through native Kotlin? I tried Kotlin's `if` and `when` but ran into type mismatch errors.

If it's possible, perhaps you can provide an example of the following use cases? Thanks very much, Ktorm has been very enjoyable to use thus far.

```
// simple case/when
case when InventoryCount > OrderQuantity then 'InStock' else 'SoldOut' end as Availability
  
// case/when comparing aggregates
case when sum(Revenue) > sum(Costs) then 'Profit' else 'Loss' end as Results
  
// aggregating single-row case/whens
sum(case when Injuries = 0 then 1 else 0 end) as InjuryFreeDays
  
// nested case/whens
case when MonthNumber = 2 then 
    case when IsLeapYear = 'Y' then 29 else 28 end
  when MonthNumber in (4,6,9,11) then 30
  else 31 end as DaysInMonth
```

**Comment by vincentlauvlwj** [comment]
No plan to support this feature.
