### ISSUE TITLE
Make same request multiple time

### ISSUE THREAD

**Issue by MacaronFR** [kotlin-orm/ktorm#395]
I have a pretty simple request that i must execute a lot of time with some parameters changing at each execution.
Does Ktorm already provide a trick to do that operation efficiently because I face a serious problem of execution time with the basic DSL.
(Several second for less than 100 request)
If no other solution exist can you consider adding a parameterized query option into Ktorm. Thanks.

**Comment by vincentlauvlwj** [comment]
Is this what you want? https://www.ktorm.org/api-docs/org.ktorm.dsl/batch-update.html

**Comment by MacaronFR** [comment]
Yes it's almost perfect.
Does something similar exist for select data from the DB ?
(I take note of batchUpdate because it can help me on other situation)

**Comment by vincentlauvlwj** [comment]
No such feature for select.
