### ISSUE TITLE
SQLite in-memory DB disappears after creating tables

### ISSUE THREAD

**Issue by DLochmelis33** [kotlin-orm/ktorm#396]
In-memory DBs are useful for testing. There is one problem with that when using Ktorm: tables have to be initialized, and with an in-memory DB it cannot be done in advance. Since Ktorm doesn't provide a way to create tables, I have to do that manually:
```kotlin
init {
  // ...
  database.useConnection { connection ->
      connection.createStatement().use {
          it.execute(createSubmissionsTableRawSqlText)
      }
  }
  // ...
}
```
However, when trying to access the table, I always get an exception:

`org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: t_submission)`

Apparently, there was a very similar issue in the Exposed framework (and they fixed it): https://github.com/JetBrains/Exposed/issues/726
The problem is that (as far as I get it) when the connection is closed, the in-memory DB is immediately deleted.

I have tried storing a connection in a variable so that it doesn't get closed, but that didn't help.

(By the way, that same code works fine when using a file DB.)

**Comment by vincentlauvlwj** [comment]
This is because SQLite in-memory DB clears the everything after the connection closed. 

To avoid this problem, you need to use only one SQLite connection in the application and never close it, check the code here: 

```kotlin
object Global {
    // Create a connection when it's first used.
    val connection = DriverManager.getConnection("jdbc:sqlite::memory:")

    init {
        // Add a shutdown hook to the connection when the application exits.
        Runtime.getRuntime().addShutdownHook(
            thread(start = false) {
                connection.close()
            }
        )
    }
}
```

Then create the Ktorm `Database` object like this: 

```kotlin
val database = Database.connect {
    object : Connection by Global.connection {
        override fun close() {
            // Override the close function and do nothing, keep the connection open.
        }
    }
}
```
