### ISSUE TITLE
How to work with JSON data?

### ISSUE THREAD

**Issue by talhaurganci** [kotlin-orm/ktorm#397]
Hello. I am working on a Kotlin project and I use Ktorm framework. This is my first Kotlin project and i am not very professional. So sorry if i cant figure out something easy but i need some help. So i have a database that i connect in the application and i have to retrieve json data from that database. But i dont know how to do that. I tried to do with objectmapper but i dont understand the exact method for it. I tried to do with a function but its not getting the json data properly. I think i get those datas to a list object. But i need the value of that index not the whole data in it. I hope i can express myself clearly so u dont get confused. Here is the screenshots for you to figure it out. JSON data im trying to read is answers column name. Any help would be greatly appreciated. Thank you :)
![gadsgads](https://user-images.githubusercontent.com/65421059/170805214-94d5c653-c013-47b7-a8cf-db2c7f3e7cd4.PNG)
![hea](https://user-images.githubusercontent.com/65421059/170805215-085ec44c-92e1-4efe-b786-5ff7b07a7ffb.PNG)
![hrahrae](https://user-images.githubusercontent.com/65421059/170805216-8a96fcca-a697-41af-b8e9-299b706890b5.PNG)
![rhae](https://user-images.githubusercontent.com/65421059/170805218-891a966f-9d3e-4b45-95cc-a18e49f88ece.PNG)
![hrae](https://user-images.githubusercontent.com/65421059/170805220-bac71a18-4180-40c2-89a4-d1314025d21b.PNG)
![haha](https://user-images.githubusercontent.com/65421059/170805221-1f1042cb-30ed-4896-9bf2-0e53d66abf93.PNG)
![Screenshot_1653702agdad425](https://user-images.githubusercontent.com/65421059/170805320-2a71f860-58b6-4a2b-8295-eef8d1005e51.png)

**Comment by vincentlauvlwj** [comment]
The code in your screenshot is correct. I don't really get what your question is.

**Comment by talhaurganci** [comment]
Hello sir! Thank you for your fast response. Yes it is correct but what i need is for example in the first button, i have to set the Baldan value. Not the whole AnswerMapper("tr": "Baldan", "en": "From Honey", "is_correct": false. I mean i need only the 1st element of the json object which is for example "Baldan". How can i achieve that? For the second button, it should set the text Sirkeden. For 3rd button Kaymaktan and for the last button Tereyağından. En= part is the english translation for those words. I will check the language entity and put them for which language is selected. True and false values is for their boolean value for being correct or the wrong answer. Thank you for your help

**Comment by vincentlauvlwj** [comment]
```kotlin
val answers = row[Question_Optionns.answers] ?: emptyList()
option1.text = answers[0].tr
option2.text = answers[1].tr
option3.text = answers[2].tr
option4.text = answers[3].tr
```

**Comment by talhaurganci** [comment]
Thank you very much! Works like a charm. I tought i would need some external class or something to parse the JSON data. But that would do :). Thank you again for your time.
