### ISSUE TITLE
scenarios for entity class serialization?

### ISSUE THREAD

**Issue by Anivie** [kotlin-orm/ktorm#398]
I'm developing a C/S application and using ktorm on the S side to manage the complex data.

 I noticed that the official website mentioned that attributes of entity classes can be serialized and transferred with networks, so I tried to implement the Serializable interface with a common class (internal data structure is consistent with entity class), and then converted the serialized data of entity classes back to normal classes, but i got an error：

`class jdk.proxy3.$Proxy3 cannot be cast to class MyData (jdk.proxy3.$Proxy3 is in module jdk.proxy3 of loader 'app'; MyData is in unnamed module of loader 'app')`

I want to transferring data directly between the client side and the server side instead of repeatedly converting data classes,is mean that I have to introduce this framework dependency on the client side?

**Comment by vincentlauvlwj** [comment]
If you insist on serializing the data via JDK serialization, yes, you have to introduce Ktorm dependency on the client side, and share the entity class between server & client. 

But I have a better solution for you. A good practice of transfering data for C/S applications is using JSON format, and Ktorm also supports JSON serialization. Here is an example. 

Server side: 

```kotlin
interface User : Entity<User> {
    var id: Long
    var name: String
    var avatar: String
}

fun test(user: User) {
    // KtormModule is an extension for Jackson, you need to add "org.ktorm:ktorm-jackson:${ktorm.version}" to your dependencies. 
    val objectMapper = ObjectMapper().registerModule(KtormModule())
    val json = objectMapper.writeValueAsString(user)
    sendDataToClient(json)
}
```

Client side: 

```kotlin
data class User(val id: Long, val name: String, val avatar: String)

fun test() {
    val json = readDataFromServer()
    // Use any JSON library you perfer to parse the data, for example Gson. 
    val user = new Gson().fromJson(json, User::class.java)
}
```

**Comment by Anivie** [comment]
> If you insist on serializing the data via JDK serialization, yes, you have to introduce Ktorm's dependency on the client side, and share the entity class between server & client.
> 
> But I have a better solution for you. A good practice of transfering data for C/S applications is using JSON format, and Ktorm also supports JSON serialization. Here is an example.
> 
> Server side:
> 
> ```kotlin
> interface User : Entity<User> {
>     var id: Long
>     var name: String
>     var avatar: String
> }
> 
> fun test(user: User) {
>     // KtormModule is an extension for Jackson, you need to add "org.ktorm:ktorm-jackson:${ktorm.version}" to your dependencies. 
>     val objectMapper = ObjectMapper().registerModule(KtormModule())
>     val json = objectMapper.writeValueAsString(user)
>     sendDataToClient(json)
> }
> ```
> 
> Client side:
> 
> ```kotlin
> data class User(val id: Long, val name: String, val avatar: String)
> 
> fun test() {
>     val json = readDataFromServer()
>     // Use any JSON library you prefer to parse the data, for example Gson. 
>     val user = Gson().fromJson(json, User::class.java)
> }
> ```

Thanks.But i am trying to make a 'no json' server using protobuf and serialization,so i have to try to introduce this dependency ,do you plan to add support with protobuf or jsonb?

**Comment by vincentlauvlwj** [comment]
no such plan
