### ISSUE TITLE
对于这种复杂sql，ktorm 是否可以支持呢？

### ISSUE THREAD

**Issue by hhhxxjj** [kotlin-orm/ktorm#408]
对下列复杂查询， ktorm 是否可以支持呢？

SELECT
    ta.s,
    JSON_OBJECT('arr',CONCAT('[',ta.arr,']'),'tId',ta.s,'alarm',ta.v,'substation', tb.department,'cab', SUBSTRING_INDEX(tb.cabloop,'_',1),'loop', SUBSTRING_INDEX(tb.cabloop,'_',-1),'load', tb.name,'protection', tb.protection,'name',JSON_UNQUOTE(JSON_EXTRACT(ta.v,'$.name')),'time',ta.t,'checked',IFNULL(JSON_UNQUOTE(JSON_EXTRACT(ta.v,'$.checked')),'')) o
FROM
    (
        SELECT DISTINCT
            (t0.s) s   ,
            MIN(t0.t) t,
            SUBSTRING_INDEX(GROUP_CONCAT(t0.v ORDER BY t0.k DESC SEPARATOR '='),'=',1) v,
            GROUP_CONCAT(t0.v ORDER BY t0.k DESC) arr
        FROM
            (
                SELECT *
                                                                                              ,
                    CONCAT(JSON_UNQUOTE(JSON_EXTRACT(v,'$.tId')), JSON_EXTRACT(v,'$.sn')) AS s,
                    JSON_UNQUOTE(JSON_EXTRACT(v,'$.t'))                                   AS t
                FROM
                    \`curve.trigger\`
                WHERE
                    ${alarmFilterArr.join(' and ')}
                AND v                    LIKE '%Lod%YX1___%' ) t0
        GROUP BY
            t0.s
        ORDER BY
            t0.t DESC,
            t0.k DESC) ta
LEFT JOIN
    (
        SELECT
            t1.tId                                              ,
            t1.name                                             ,
            SUBSTRING_INDEX(t1.org_id,'_',-2) cabloop           ,
            JSON_UNQUOTE(JSON_EXTRACT(t3.v,'$.name')) department,
            GROUP_CONCAT(JSON_UNQUOTE(JSON_EXTRACT(t2.v,'$.name'))) protection
        FROM
            (
                SELECT
                    SUBSTRING_INDEX(JSON_UNQUOTE(JSON_EXTRACT(v,'$.key')),'/',1) tId,
                    JSON_UNQUOTE(JSON_EXTRACT(v,'$.name')) name                     ,
                    JSON_UNQUOTE(JSON_EXTRACT(v,'$.ds_ids')) ds_ids                 ,
                    JSON_UNQUOTE(JSON_EXTRACT(v,'$.org_id')) org_id
                FROM
                    \`${gatewayId}.ambient\`.\`config.terminalExtra\`
                WHERE
                    k LIKE 'Lod-01%') t1
        LEFT JOIN
            (
                SELECT *
                FROM
                    \`${gatewayId}.ambient\`.\`config.terminalExtra\`
                WHERE
                    k NOT LIKE 'Lod-01%') t2
        ON
            LOCATE(t2.k,t1.ds_ids)>0
        LEFT JOIN
            \`${gatewayId}.ambient\`.\`config.department\` t3
        ON
            SUBSTRING_INDEX(t1.org_id,'_',3)=t3.k
        WHERE
            JSON_UNQUOTE(JSON_EXTRACT(t2.v,'$.device_class_id')) LIKE '%10030501%'
        OR  JSON_UNQUOTE(JSON_EXTRACT(t2.v,'$.device_class_id')) LIKE '%10030503%'
        GROUP BY
            t1.tId) tb
on
    SUBSTRING_INDEX(ta.s,'.',1)=tb.tId
ORDER BY
    ta.t DESC,
    ta.s LIMIT ${(current - 1) * pageSize},${pageSize};

我设想了一个实现方法，不知道是否可行？

先看大查询，from 子句的第一部分：

SELECT DISTINCT
            (t0.s) s   ,
            MIN(t0.t) t,
            SUBSTRING_INDEX(GROUP_CONCAT(t0.v ORDER BY t0.k DESC SEPARATOR '='),'=',1) v,
            GROUP_CONCAT(t0.v ORDER BY t0.k DESC) arr
        FROM
            (
                SELECT *
                                                                                              ,
                    CONCAT(JSON_UNQUOTE(JSON_EXTRACT(v,'$.tId')), JSON_EXTRACT(v,'$.sn')) AS s,
                    JSON_UNQUOTE(JSON_EXTRACT(v,'$.t'))                                   AS t
                FROM
                    \`curve.trigger\`
                WHERE
                    ${alarmFilterArr.join(' and ')}
                AND v                    LIKE '%Lod%YX1___%' ) t0
        GROUP BY
            t0.s
        ORDER BY
            t0.t DESC,
            t0.k DESC) ta

初步想的实现方法是：

 SELECT *
                                                                                              ,
                    CONCAT(JSON_UNQUOTE(JSON_EXTRACT(v,'$.tId')), JSON_EXTRACT(v,'$.sn')) AS s,
                    JSON_UNQUOTE(JSON_EXTRACT(v,'$.t'))                                   AS t
                FROM
                    \`curve.trigger\`
                WHERE
                    ${alarmFilterArr.join(' and ')}
                AND v                    LIKE '%Lod%YX1___%' ) t0

1. 这个用 ktorm 可以简单 转化为 一个 Query；
2. 但这个Quey 又出现在上级的 select 语句中，所以焦点问题是，这个query 是否可以转换为 QuerySource？ 
个人认为从技术上应该是 OK的， 因为from 子句select 后也就是一个 ResultSet， Query后面也就是一个ResultSet。
是否提供一个简单的 asSource， 就可以支持这个语法了？

如果这个 asSource 是可以的，后面好像就没有任何技术障碍了。

针对这个结果，继续asSource 后，根据ktOrm 的设计，source 支持left join， 所以就可以继续操作，从而完成整体问题。

前面我们团队的人说，这样的查询，需要用 原始sql 写上两天，还特别容易出错，我觉得这里主要是sql用起来不自然。 如果ktOrm能够象以上这样支持，或许15分钟就可以写完整个查询了。

**Comment by hhhxxjj** [comment]
这个可能是应用中真正的需求。 要不，针对简单的 sql，往往手写其实也行；或者，虽然用了 orm 框架，但面对复杂的查询，还是需要将 sql 抬出来，使得ktorm 这样的框架没有发挥真正作用

**Comment by hhhxxjj** [comment]
如果成立，是否 QuerySource 这个概念没有必要存在。从代码看， QuerySource 主要是 根据Table 建立， 而针对只读查询，Query也可以看作一个只读Table。 

当然，由于innerJoin，等操作比较特殊，保持 QuerySource 等可能更好

**Comment by vincentlauvlwj** [comment]
这个在技术上当然是可以实现的，而且我以前也实现过一个版本，但是最终我还是没有合并进来，主要是考虑到 ktorm 的定位只是为了简化大部分常见的数据库操作，不是为了替代 SQL。如此复杂的 SQL 语句，大部分 ORM 框架都不会有良好的支持，就算勉强实现了，往往体验也不会太好

我个人的建议，如果在你的项目中，这种复杂 SQL 只是一个特例，在少数场景下才会出现，你可以选择使用 Ktorm 的[原生 SQL 支持](https://www.ktorm.org/zh-cn/dialects-and-native-sql.html#%E5%8E%9F%E7%94%9F-SQL)，但如果你的项目中存在大量的复杂 SQL，我想你们或许不适合使用 ORM 框架，改用 MyBatis 这样的 SQL 映射框架可能是更好的选择

**Comment by hhhxxjj** [comment]
将tableAlias 从 val 改为 var， 然后新加一个函数：
    fun QueryExpression.aliased(s: String) : QueryExpression{
        this.tableAlias = s
        return this
    }

整个过程似乎就可以work了，测试如下：



   class MyTables : Table<Nothing>("myTable") {
        val name = varchar("hello")
    }

    @Test
    fun testBetween() {
        val t = Employees.aliased("x")
        val s = database.from(t)
        println(s.expression)
        val x1 = s.select(t.name.aliased("hello"))
        val x = x1.where { t.salary between 100L..200L }
        println(x.sql)
        val names = x.map { it.getString(1) }
        assert(names.size == 3)
        println(names)

        // 这个似乎成功了, hhh, 2022.7.10
        val t0 = MyTables()
        val s2 = QuerySource(database, t0, x.expression.aliased("myTable"))
        val x2 = s2.select(t0.name)
        val names2 = x2.map { it.getString(1) }
        println(x2.sql)
        assert(names2.size == 3)
    }

测试结果：
SELECT "myTable"."hello" AS "myTable_hello" 
FROM (
  SELECT "x"."name" AS "hello" 
  FROM "t_employee" "x" 
  WHERE "x"."salary" BETWEEN ? AND ?
) "myTable" 

这么改动是否 OK？

**Comment by hhhxxjj** [comment]
> 

感谢回复。 
>> 如此复杂的 SQL 语句，大部分 ORM 框架都不会有良好的支持
我比较了很多个ORM 框架，觉得 ktorm 做的最棒。
但从我自己的例子来看，如果内容很简单，其实用不用框架都无所谓； 真正复杂的，框架又不支持，显得框架意义大打折扣。
如果我们支持了，可能就成为我们这个框架的特色功能。

>> 上面我的实现是我随便在给的测试例子中找了一个例子改的，非常简单就可以实现。
主要不足是，**需要将 将tableAlias 从 val 改为 var， 做了这个改动后，其实就算完成了**。

这个函数如果框架不加，在用户代码中加上也是一样的。
fun QueryExpression.aliased(s: String) : QueryExpression{
this.tableAlias = s
return this
}


问题是：您觉得这个改动是否可以，是否会影响您的其他功能？ 如果可以，烦请加入，这样，我们马上就可以用ktOrm，完成很多复杂的查询功能了。

**Comment by hhhxxjj** [comment]
这个问题也是： 
https://github.com/kotlin-orm/ktorm/issues/364
提出的问题。 我看前面似乎还有若干个issue，问的都是 subquery().   

从我的经验看，似乎框架原本就是支持的，略微改动下即可

**Comment by vincentlauvlwj** [comment]
ktorm 在最初设计的时候确实是支持子查询的，但是最终开源的版本还是把这个功能去掉了，原因除了我刚刚说到的框架定位问题，还有其使用体验也不是很好，很难找到一种相对完美的实现方式

你的思路确实是可行的，你感兴趣的话可以自己尝试实现一下，但我不会把 `val` 改成 `var`，你的 `aliased` 函数完全可以换种写法，功能是一样的：

```kotlin
fun QueryExpression.aliased(s: String): QueryExpression {
    return when (this) {
        is SelectExpression -> this.copy(tableAlias = s)
        is UnionExpression -> this.copy(tableAlias = s)
    }
}
```

**Comment by hhhxxjj** [comment]
多谢。这个改动很妙。
有个地方不是很明白。 有什么功能是 基于DSL 不能实现，而一定需要基于Entity 实现的呢？
我看两者差别仅仅是：
class MyTables : Table<Nothing>
以及
class MyTables : Table<MyTable>

后者主要就是做列绑定？ 如果不做列绑定，有什么功能比较难于实现？

**Comment by hhhxxjj** [comment]
理解了，感谢：
>> 通过查询从数据库中获取实体对象的时候，Ktorm 会根据我们的绑定配置，将某个列的数据填充到它所绑定的属性中去；
在将实体对象中的修改更新到数据库中的时候（使用 flushChanges 函数），Ktorm 也会根据我们的绑定配置，将某个属性的变更，同步更新到绑定它的那个列
