### ISSUE TITLE
join 函数怎么使用多个条件匹配呢？

### ISSUE THREAD

**Issue by 891806797** [kotlin-orm/ktorm#410]
比如说下面这条SQL语句
select t_employee.name as t_employee_name, t_department.name as t_department_name 
from t_employee 
left join t_department on t_employee.department_id = t_department.id  and t_department.uid = ?
where t_employee.salary > ?

我要在left join 后面有两个或者多个过滤条件的情况下怎么处理呢？

**Comment by vincentlauvlwj** [comment]
用 and 连接

**Comment by 891806797** [comment]
多谢🙏谢谢老哥可以研发出来一款这么优秀的框架出来，如果能给一个bind函数比如：
var users:List<User> = ArrayList()
where(xx).bind(users)这样的函数就更棒了，就可以省略更多的模板代码了
