### ISSUE TITLE
Wrong ANSI SQL keyword

### ISSUE THREAD

**Issue by sephrouse** [kotlin-orm/ktorm#432]
In the set of ANSI_SQL_2003_KEYWORDS, there is a keyword called SESSION_USE in the line No. 215, seems there is a letter R missed in the end. That keyword should be SESSION_USER.

Please review and revise the keyword if it was wrong.

Thanks.

**Comment by vincentlauvlwj** [comment]
Thank you for your feedback. I've updated the SQL keywords. This will be release in the next version.

**Comment by vincentlauvlwj** [comment]
Released in 3.6.0
