### ISSUE TITLE
Question about storing timestamp (Instant) on Postgres.

### ISSUE THREAD

**Issue by shi-rudo** [kotlin-orm/ktorm#434]
Hello guys. I have the following problem or do not understand what is happening here. I use Spring 2.7.5 with KTORM 3.5.0 as ORM framework with hikariCP as pool. 

My Postgres 14.5 database table has the following properties:
```sql
create table if not exists FOO(
...
    created_at                      timestamp default now(),
    updated_at                      timestamp,
...
```

```console
postgres=> SHOW time zone;
 TimeZone 
----------
 GMT
(1 row)
```

The connection is established by hikari:
```kotlin
 val config = HikariConfig()
        config.driverClassName = "org.postgresql.Driver"
        config.jdbcUrl = "jdbc:postgresql://localhost:4000/postgres"
        ...
        config.validate()
```

The column binding declared by the KTORM interface binding is:
```kotlin
val createdAt = timestamp("created_at").bindTo { it.createdAt }
```

For the sake of testing, I save the time as follows:
```kotlin
entity.createdAt = Instant.parse("1999-12-31T23:00:00Z")
```

While the entity is written to the database, this log with statement is shown. The value passed matches the value parsed in the code snippet above.✅
```log
[DEBUG] SQL: insert into FOO (..., created_at, updated_at, ...) values (?, ?, ?, ..) 
[DEBUG] Parameters: [..., 1999-12-31T23:00:00Z(timestamp), null(timestamp) ...
```

🚨 when I query the data via SQL `postgres=> SELECT * FROM FOO;`. Just to make sure that pgAdmin or IntelliJ DataGrip don't have any time conversation on my local system (UTC+1), I have connected into the respective Docker container via terminal and executed the SQL query directly using psql console. Also pgAdmin or Datagrip return me the value 2000-01-01 00:00:00. ❌
```postgres
postgres=> SELECT * FROM FOO;
 ... | created_at          |            | ...
 ... | 2000-01-01 00:00:00 |            | ...
```

What totally confuses me is that as soon as I load the entity from the database using KTORM, the time is correct?✅
```log
[DEBUG] SQL: select ....
[DEBUG] Results: 1
Foo{..., createdAt=1999-12-31T23:00:00Z ...
```

| **action**                                  | **time value**       | **assert** |
|---------------------------------------------|----------------------|------------|
| parsed in code                              | 1999-12-31T23:00:00Z | ✅          |
| sent to postgres by KTORM                   | 1999-12-31T23:00:00Z | ✅          |
| persisted in postgres                       | 2000-01-01 00:00:00  | ❌          |
| returned by KTORM after query from postgres | 1999-12-31T23:00:00Z | ✅          |

* Can someone be so kind and explain to me why the database keeps the value of 1999-12-31T23:00:00Z in local time UST+1 (2000-01-01 00:00:00). However, as soon as I query the entity using KTORM in spring, I get the correct time displayed (1999-12-31T23:00:00Z)? 

* What do I have to do so that the value in the database matches the value in the code? I explicitly do not want to save the time zone. I want to parse a UTC value, save it as UTC and have it returned as a UTC value.

**Comment by vincentlauvlwj** [comment]
Timestamp is just a long number of millis starts from 1970-01-01 00:00 UTC+0. Displaying the same timesamp in different time zone will get different results. `java.time.Instant` displays it in UTC+0, while your psql console displays it in your local time zone (UTC+1), but whatever it's displayed, it is always the same instant value. 

If you want psql console display timestamps in UTC+0, you can try to change it's default time zone, see https://stackoverflow.com/questions/6663765/postgres-default-timezone

**Comment by vincentlauvlwj** [comment]
I think I've found the issue, code in postgresql driver 42.2.5, `PgPreparedStatement`, line 1349, using the system default time zone to format timestamps to strings before sending them to the database. 

But it seems a JDBC's documented feature instead of a bug, there is a stackoverflow link for the same problem https://stackoverflow.com/questions/14070572/is-java-sql-timestamp-timezone-specific/14070771#14070771

Anyway, it's always a good practice to make you application and database server in the same time zone. 

![image](https://user-images.githubusercontent.com/10897214/192246212-dcb3cf27-ada2-47db-b2a0-4fa2fa8fa0c4.png)
