### ISSUE TITLE
Batch query or multiple onDuplicateKey at bulkInsertOrUpdate

### ISSUE THREAD

**Issue by Gerrist** [kotlin-orm/ktorm#440]
Hi,

Is it possible to have a bulkInsertOrUpdate query where each item has its own onDuplicateKey? I want to upsert multiple rows all with different primary keys.

Or is it possible to a batch of single insertOrUpdate queries so an upsert action doesn't take 10+seconds because each insertOrUpdate requires a new connection.

Thanks!

**Comment by vincentlauvlwj** [comment]
Can you give an example for what you want to do?
