### ISSUE TITLE
Does Ktorm protect from SQL injections?

### ISSUE THREAD

**Issue by torpare** [kotlin-orm/ktorm#444]
I was looking through the documentation of Ktorm and couldn't find any reference to the topic of SQL Injections. Does using Ktorm guarantee protection against SQL injections, or not?

Does it use prepared statements under the hood?

Reading through this article https://www.baeldung.com/sql-injection i noticed that ORM:s in general in fact does **not** necessarily protect us from SQL injections: 

*"This is a common misconception. JPA and other ORMs relieves us from creating hand-coded SQL statements, but they won't prevent us from writing vulnerable code"*

**Comment by vincentlauvlwj** [comment]
Yes, of course.

**Comment by vincentlauvlwj** [comment]
Every ORM framework supports prepared statements.
