### ISSUE TITLE
controller层用java写调用方法404

### ISSUE THREAD

**Issue by hell176** [kotlin-orm/ktorm#451]
![image](https://user-images.githubusercontent.com/74386505/203691244-f34cf9ee-2479-45d3-8bbf-2837b1988fb5.png)
springboot项目整合了ktorm，kotlin的get方法可以访问，java的就404，这是什么原因？有什么办法解决

**Comment by michaelfyc** [comment]
>  java的就404

这是什么意思，能详细描述一下么🤔
（我不是项目的维护者，不保证能解决你的问题）

**Comment by diantongren** [comment]
java的代码应该放在src/main/java下吧

**Comment by 2938137849** [comment]
java的代码应该src/main/java，否则你需要添加编译参数让kotlin文件夹下的java代码参与编译

**Comment by vincentlauvlwj** [comment]
> java的代码应该放在src/main/java下吧

正解
