### ISSUE TITLE
kotlinx-serializable

### ISSUE THREAD

**Issue by diantongren** [kotlin-orm/ktorm#454]
ktorm目前是不支持kotlinx-serializable吧？
不知道在哪加`@Serializable`

**Comment by michaelfyc** [comment]
是的，请看 #3 😂 
根据官方文档：
> ...Ktorm provides an Entity.create function, which generates implementations for entity interfaces via JDK dynamic proxy, and creates their instances for us.

由于 ktorm 生成的 Entity 是一个 proxy 对象，因此你在自己定义的 entity 上添加 `@Serializable` 是没用的。不知道 data class 行不行，我没试过🤔。有兴趣的话可以一起研究一下，提个 pr？

**Comment by vincentlauvlwj** [comment]
确实不支持，只支持 JDK 序列化
