### ISSUE TITLE
关于日志建议

### ISSUE THREAD

**Issue by Xiaobaishushu25** [kotlin-orm/ktorm#455]
请问开启日志后可以显示查询结果吗（不是像results这样的结果数量），我没有找到相关设置，如果没有，我觉得加上结果挺有用的。谢谢您的框架，很nice
![image](https://user-images.githubusercontent.com/76581880/205093886-fd4a500c-f145-4b8d-9ca5-792b9d096705.png)

**Comment by vincentlauvlwj** [comment]
你只需要把 trace 日志打开就可以了 https://www.ktorm.org/zh-cn/connect-to-databases.html#%E6%97%A5%E5%BF%97%E8%BE%93%E5%87%BA
