### ISSUE TITLE
插入的对象为空时,实际没有插入对象

### ISSUE THREAD

**Issue by openaddr** [kotlin-orm/ktorm#457]
当调用public fun <E : Entity<E>, T : Table<E>> EntitySequence<E, T>.add(entity: E): Int方法时,如果entity对象没有设置任何属性,则没有执行插入语句.
但预期是插入一行空数据,
例如
```
object Ids : Table<Id>("ids") {
    val id = long("id").bindTo { it.id }.primaryKey()
    var createTime = datetime("create_time").bindTo { it.createTime }
    var updateTime = datetime("update_time").bindTo { it.updateTime }
    var isDeleted = boolean("is_deleted").bindTo { it.isDeleted }
}
```
```
interface Id : Entity<Id> {
    companion object : Entity.Factory<Id>()

    val id: Long
    var createTime : LocalDateTime
    var updateTime : LocalDateTime
    var isDeleted : Boolean
}
```
```
    val Database.ids get() = this.sequenceOf(Ids)
    val id = Id()
    database.ids.add(id) //执行此行代码时,预期是在数据库中插入一行空数据,但实际上没有进行任何操作
```
而调用
    database.insertAndGenerateKey(???){
        //这里不设置任何属性
    }
时,则没有这个问题(即成功插入了一行空数据)

**Comment by diantongren** [comment]
文档里说了不赋属性，生成的sql就会忽略字段
> ...可以看到，生成的 SQL 包含了 Employee 实体对象中的所有已赋值的属性，如果我们将某个字段的赋值代码去掉，那么生成的 insert SQL 中就不会出现这个字段。例如，创建实体对象时只设置员工名称 `Employee { name = "jerry" }`，那么生成的 SQL 也只会插入这一个字段 `insert into t_employee (name) values (?)`。

```kotlin
@Suppress("UNCHECKED_CAST")
public fun <E : Entity<E>, T : Table<E>> EntitySequence<E, T>.add(entity: E): Int {
    checkForDml()
    entity.implementation.checkUnexpectedDiscarding(sourceTable)

    val assignments = entity.findInsertColumns(sourceTable).takeIf { it.isNotEmpty() } ?: return 0

    val expression = AliasRemover.visit(
        expr = InsertExpression(
            table = sourceTable.asExpression(),
            assignments = assignments.map { (col, argument) ->
                ColumnAssignmentExpression(
                    column = col.asExpression() as ColumnExpression<Any>,
                    expression = ArgumentExpression(argument, col.sqlType as SqlType<Any>)
                )
            }
        )
    )
……
```
还有我试了一下database.insertAndGenerateKey(){} 不设置值话会报错

**Comment by openaddr** [comment]
![屏幕截图 2022-12-05 182611](https://user-images.githubusercontent.com/61171538/205614419-d9238347-19ce-4e4b-bd7e-fad920f1d73e.png)
当调用database.insertAndGenerateKey(Ids){} 方法时,从控制台可以看到生成了SQL
 INSERT INTO ids () VALUES () 
插入了一行空数据(因为数据库配置了id自增,所以实际上数据库生成了一行新数据,包含了id字段),这正是我想要的


"如果我们将某个字段的赋值代码去掉，那么生成的 insert SQL 中就不会出现这个字段。"
这句话是符合预期的,但如果整个对象中不包含任何字段的话,它并非生成了一条不包含字段的insert SQL,而是直接没有生成SQL.传入空对象的时候,是否也应该生成一条类似
 INSERT INTO ids () VALUES () 
的SQL呢

**Comment by openaddr** [comment]
受教了,谢谢!

**Comment by vincentlauvlwj** [comment]
谢谢反馈，这里的确有 bug，不管是 dsl 的 `insert` 方法还是 sequence 的 `add` 方法，目前的行为都是不正确的，更好的做法是检查到插入语句的字段列表为空时，直接抛出异常，而不是忽略或者勉强生成 SQL

严格来说，`INSERT INTO ids () VALUES ()` 这种 SQL 是未定义行为，有些数据库允许这种写法，也有些数据库会报语法错误，SQL 标准参见 [SQL 2003 BNF](https://ronsavage.github.io/SQL/sql-2003-2.bnf.html#insert%20statement)

因此，最好的做法其实是抛出异常，后面的版本会考虑修改

**Comment by vincentlauvlwj** [comment]
3.6.0 版本已发布
