### ISSUE TITLE
Database如何支持spring@Lazy

### ISSUE THREAD

**Issue by eddy-gao** [kotlin-orm/ktorm#461]
Database 类是final的，使用spring@Lazy的时候报错

**Comment by vincentlauvlwj** [comment]
你可以自己写一个类，把 `Database` 包起来

**Comment by eddy-gao** [comment]
> 你可以自己写一个类，把 `Database` 包起来

@vincentlauvlwj 可以。ktorm有打算解决这个问题么？

**Comment by vincentlauvlwj** [comment]
没有这个打算，`Database` 不是为继承而设计的，open class 会一定程度破坏封装性，之前的 inline 函数也没法内联
