### ISSUE TITLE
referencing N:M, 1:N relations (referencing a List)

### ISSUE THREAD

**Issue by vogthenn** [kotlin-orm/ktorm#470]
In the documentation I can't seem to find how to reference a list, and I don't get it.  What I'm asking for is basically how tor eference N:M (*:*) relations, or 1:M (1:*) relations. Following setup

and for M:N (many Contracts can have many approvers, needed if you always have the same few approvers that need o approve all the contracts)

    interface Contract : Entity<Contract> {
            val id: Long
            val approvers: List<Person>
    }

    // do we need an interface for the relation table?
    interface ContractToPerson: Entity<ContractToPerson> {
        val contractId: Long  // could be a list if you want to look up what contracts were approved by a Person...
        val approvers: List<Person>  // for my example I only need to lookup whether a _Contract_ was approved
    }

    interface Person : Entity<Person> {
       val contractId: Long
       val name: String
    }

in the end I want to use .references method for filling the List<Person> in Contract... but I don't get how I could even start to do that.
Any help highly appreciated!

**Comment by vincentlauvlwj** [comment]
M:N & 1:N relations have heavy impact on performance, it may lead to n+1 problem implicitly, my suggestion is to load the list manually: 

```kotlin
interface Contract : Entity<Contract> {
    val id: Long

    val approvers: List<Person> get() {
        return database.persons.filter { some conditions }.toList()        
    }
}
```
