### ISSUE TITLE
Select max doesn't work correctly

### ISSUE THREAD

**Issue by olexanje** [kotlin-orm/ktorm#474]
in **mySQL** if you make query you need to write **_"SELECT MAX(column_name) FROM database_name.table_name"_**. 
If you not write **_database_name_** in query you will receive  _"Error Code: 1046. No database selected Select the default DB to be used by double-clicking its name in the SCHEMAS list in the sidebar."_
In program **_println(query.sql)_**  prints:
_**select max(table_name.column_name) 
from table_name**_
and returning **_null_**.
(val query = database.from(TableNameObject).select(max(TableNameObject.columnName))

**Comment by vincentlauvlwj** [comment]
@diantongren's suggestion is correct, but you can also specify the schema in the connection url, for example: 

```text
jdbc:mysql://localhost:3306/DATABASE_NAME
```
