### ISSUE TITLE
有社区群吗

### ISSUE THREAD

**Issue by zz541843** [kotlin-orm/ktorm#476]

**Comment by vincentlauvlwj** [comment]
我个人不太喜欢微信群和 QQ 群之类的，直接在 GitHub 讨论即可

**Comment by zz541843** [comment]
> 我个人不太喜欢微信群和 QQ 群之类的，直接在 GitHub 讨论即可

这个库不能自动建表吗？找了好久没找到

**Comment by vincentlauvlwj** [comment]
不能

**Comment by zz541843** [comment]
> 不能

自定义接口继承entity，有个create_date字段，每次insert都要手动赋值，怎么做到自动插入某值？取出的时候也自动转成string
