### ISSUE TITLE
Pass object instead of properties to insert method

### ISSUE THREAD

**Issue by mjovanc** [kotlin-orm/ktorm#481]
Is it possible currently to instead of defining each value, just pass in an object? Currently there is this:

```kotlin
database.insert(Employees) {
    set(it.name, "jerry")
    set(it.job, "trainee")
    set(it.managerId, 1)
    set(it.hireDate, LocalDate.now())
    set(it.salary, 50)
    set(it.departmentId, 1)
}
```

Would it be possible to do something like this:

```kotlin
database.insert(Employees) {
    setObj(employee)
}
```

I've already defined my entity and would be good to use that to pass it in instead of hard coding it.

**Comment by vincentlauvlwj** [comment]
Use `database.employees.add()`

**Comment by mjovanc** [comment]
Great! Thank you
