### ISSUE TITLE
原生 SQL 只能从select * 开始写吗？

### ISSUE THREAD

**Issue by zz541843** [kotlin-orm/ktorm#485]
也不是很特殊的情况下，也会用到原生sql吧，只需要提供一个插槽，规定的地方调用传进去的字符串就行了，不然很长的一段sql因为orm框架不支持自定义sql而需要全部手写，太不友好了
我现在需要通过一个json字段的属性来筛选，目前ktorm的首先不支持自定义sql，其次，运算符虽然支持自定义，但是局限性很大，只能传进来一个值，类型只能是那些类型，json like这个场景就得额外需要一个json指定 属性的参数
目前我还没看源码，感觉ScalarExpression这个类改改应该能多一点自由度

**Comment by zz541843** [comment]
稀里糊涂的看到ktorm，这么灵活，稀里糊涂的就用上了，公司新项目就用的springboot3和ktorm，可别到最是手写sql啊😹😹😹

**Comment by vincentlauvlwj** [comment]
Ktorm 支持原生 SQL，但不建议使用，Ktorm 的灵活性足够扩展出你想要的大多数写法

**Comment by vincentlauvlwj** [comment]
大多数写法 (子查询除外 :disappointed_relieved:)

**Comment by zz541843** [comment]
ktorm的源码可以先从哪些地方下手？我打算加入一下

**Comment by vincentlauvlwj** [comment]
欢迎，源码不多，全部通读一遍也花不了多少时间
