### ISSUE TITLE
序列关闭默认连表，查询的时候怎么手动指定？

### ISSUE THREAD

**Issue by zz541843** [kotlin-orm/ktorm#488]
this.sequenceOf(xx, withReferences = false) 设置了，序列find查询怎么手动指定我需要关联的表？

**Comment by vincentlauvlwj** [comment]
如果 `withReferences` 为 false，不会关联表

**Comment by zz541843** [comment]
> 如果 `withReferences` 为 false，不会关联表，既然不会关联，这个问题从何而来？

我一张表要关联很多其他的表，不同业务返回不同的关联对象，如果withReferences=true，序列查询不是全都会查出来吗，所以既然withReferences可以设置成false，那么在序列的查询中，怎么指定我这次需要关联哪张表

**Comment by vincentlauvlwj** [comment]
不需要查询的表，在绑定的时候不要用 `references`，改为 `bindTo` 绑定到对应关联表的主键

**Comment by zz541843** [comment]
哇，我看了好一会儿的源码，其实一直觉得不难，但就是给我绕晕了，啊...
