### ISSUE TITLE
序列使用关联表做条件报错

### ISSUE THREAD

**Issue by zz541843** [kotlin-orm/ktorm#491]
![image](https://user-images.githubusercontent.com/72638366/225865012-7caac7c7-f42e-42c6-8f61-598aab3decef.png)

val deviceId = int("device_id").references(Devices) { it.deviceInfo }.bindTo { it.deviceId }
val devices get() = deviceId.referenceTable as Devices

通过一个id字段去references并bindTo，这两个函数无论哪个在前面，都无法解决查询和获取同时有效，如果references在前面的话，find的时候的条件使用devices.xx eq xx，就会报错

**Comment by vincentlauvlwj** [comment]
代码和错误信息发一下

**Comment by zz541843** [comment]
> 代码和错误信息发一下

    val deviceId = int("device_id").bindTo { it.deviceId }.references(DeviceTable) { it.deviceInfo }
    val deviceTable = deviceId.referenceTable as DeviceTable

最终有个完美的效果：能通过序列查询的时候能通过deviceTable.xx 去做条件，现在会报错
java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type com.example.springbootdemo1.database.table.DeviceTable

也能直接赋予一个关联表的对象，add的时候能一起插入，但此时referrences在后面，做不到
库的限制也不能新写两行一样的int("device_id")一个bind一个referrences，只能做二选一
