### ISSUE TITLE
关于返回的时间数据问题

### ISSUE THREAD

**Issue by PingerAI** [kotlin-orm/ktorm#500]
映射了数据库
interface InOutRecordInfo: Entity<InOutRecordInfo> {
    companion object : Entity.Factory<InOutRecordInfo>()
    val id : Int
    var type : Int
    var count : Int
    var operatorId:Int
    var operatorName:String
    var createTime:LocalDateTime
    var shouldReceipts:Double
    var actualReceipts:Double
    var remark:String
    var settle:Int
    var productId:Int
    var buyerId:Int
}
查询后返回的数据类型采取的是InOutRecordInfo这个，但是接口返回后并不是yy-mm-dd hh:mm:ss的时间字符串格式，是否有类似@JsonFormat这种的方式，当通过接口返回给前端的时候自动把LocalDateTime转换成yy-mm-dd hh:mm:ss的时间字符串格式

**Comment by vincentlauvlwj** [comment]
另外写一个 DTO，把实体类数据转为 DTO，再把 DTO 返回给前端

**Comment by PingerAI** [comment]
也就是说，当数据库映射的类中有时间类型的时候我都需要重新创建一个实体类才行

**Comment by vincentlauvlwj** [comment]
从编码规范来说，所有实体类不要直接返回给前端，而是通过 DTO 对象返回

**Comment by PingerAI** [comment]
OK，感谢
