### ISSUE TITLE
Entity 如何设置自定义的 JsonSerializer

### ISSUE THREAD

**Issue by ParadiseHell** [kotlin-orm/ktorm#515]
```kotlin
interface TestEntity {
  val config : String
}
```

我的 config 是个 json, 我想序列化的时候直接序列化成 json 对象，自定义了一个 JsonSerializer, 加了注解失败了，我看源码没有 check 字段时候有 JsonSerialize 注解。

**Comment by onXoot** [comment]
假如你的 config 是个json , 定义一个
```
data class MyConfig(val name: String, val conf: String)
```
定义 entity
```
interface TestEntity : org.ktorm.entity.Entity<TestEntity> {
    val id: Long
    val config : MyConfig // 这里是自定义config
    val configMap: Map<String, *> // 或者你想直接用map 
}
```

自定义转换器
```
object MyConfigType : SqlType<MyConfig>(Types.VARCHAR, "myConfig") {
    private val objectMapper = com.fasterxml.jackson.databind.ObjectMapper()
    override fun doSetParameter(ps: PreparedStatement, index: Int, myConf: MyConfig) {
        ps.setString(index, if (myConf == null) "{}" else objectMapper.writeValueAsString(myConf))
    }
    override fun doGetResult(rs: ResultSet, index: Int): MyConfig? {
        return rs.getString(index)?.let { objectMapper.readValue(it, MyConfig::class.java) }
    }
}

// Map 类型需要定义 TypeReference
class MyConfigMapRef: com.fasterxml.jackson.core.type.TypeReference<Map<String, *>>()

object MyConfigMapType : SqlType<Map<String, *>>(Types.VARCHAR, "myConfigMap") {
    private val myConfigMapType: TypeReference<Map<String, *>> =  MyConfigMapRef()
    private val objectMapper = com.fasterxml.jackson.databind.ObjectMapper()
    override fun doSetParameter(ps: PreparedStatement, index: Int, myConfMap: Map<String, *>) {
        ps.setString(index, if (myConfMap == null) "{}" else objectMapper.writeValueAsString(myConfMap))
    }
    override fun doGetResult(rs: ResultSet, index: Int): Map<String, *>? {
        return rs.getString(index)?.let { objectMapper.readValue(it, myConfigMapType) }
    }
}
```
然后注册自定义转换器
```
fun <E : Any> BaseTable<E>.myConfig(name: String): org.ktorm.schema.Column<MyConfig> {
    return registerColumn(name, MyConfigType)
}

fun <E : Any> BaseTable<E>.myConfigMap(name: String): org.ktorm.schema.Column<Map<String, *>> {
    return registerColumn(name, MyConfigMapType)
}
```

然后就可以使用了
```
object TestEntitys: org.ktorm.schema.Table<TestEntity>("test_table") {
    val id = long("id").primaryKey().bindTo { it.id }
    val config = myConfig("config").bindTo { it.config }
    val configMap = myConfigMap("config_map").bindTo { it.configMap }
}
```
在dao 里可以直接使用
```
    fun getConfById(id: Long): TestEntity? {
        val testConf = db.sequenceOf(TestEntitys).find { it.id eq id }
        val config =  testConf?.config
        val configMap = testConf?.configMap
        return testConf
    }
```

**Comment by ParadiseHell** [comment]
> 假如你的 config 是个json , 定义一个
> 
> ```
> data class MyConfig(val name: String, val conf: String)
> ```
> 
> 定义 entity
> 
> ```
> interface TestEntity : org.ktorm.entity.Entity<TestEntity> {
>     val id: Long
>     val config : MyConfig // 这里是自定义config
>     val configMap: Map<String, *> // 或者你想直接用map 
> }
> ```
> 
> 自定义转换器
> 
> ```
> object MyConfigType : SqlType<MyConfig>(Types.VARCHAR, "myConfig") {
>     private val objectMapper = com.fasterxml.jackson.databind.ObjectMapper()
>     override fun doSetParameter(ps: PreparedStatement, index: Int, myConf: MyConfig) {
>         ps.setString(index, if (myConf == null) "{}" else objectMapper.writeValueAsString(myConf))
>     }
>     override fun doGetResult(rs: ResultSet, index: Int): MyConfig? {
>         return rs.getString(index)?.let { objectMapper.readValue(it, MyConfig::class.java) }
>     }
> }
> 
> // Map 类型需要定义 TypeReference
> class MyConfigMapRef: com.fasterxml.jackson.core.type.TypeReference<Map<String, *>>()
> 
> object MyConfigMapType : SqlType<Map<String, *>>(Types.VARCHAR, "myConfigMap") {
>     private val myConfigMapType: TypeReference<Map<String, *>> =  MyConfigMapRef()
>     private val objectMapper = com.fasterxml.jackson.databind.ObjectMapper()
>     override fun doSetParameter(ps: PreparedStatement, index: Int, myConfMap: Map<String, *>) {
>         ps.setString(index, if (myConfMap == null) "{}" else objectMapper.writeValueAsString(myConfMap))
>     }
>     override fun doGetResult(rs: ResultSet, index: Int): Map<String, *>? {
>         return rs.getString(index)?.let { objectMapper.readValue(it, myConfigMapType) }
>     }
> }
> ```
> 
> 然后注册自定义转换器
> 
> ```
> fun <E : Any> BaseTable<E>.myConfig(name: String): org.ktorm.schema.Column<MyConfig> {
>     return registerColumn(name, MyConfigType)
> }
> 
> fun <E : Any> BaseTable<E>.myConfigMap(name: String): org.ktorm.schema.Column<Map<String, *>> {
>     return registerColumn(name, MyConfigMapType)
> }
> ```
> 
> 然后就可以使用了
> 
> ```
> object TestEntitys: org.ktorm.schema.Table<TestEntity>("test_table") {
>     val id = long("id").primaryKey().bindTo { it.id }
>     val config = myConfig("config").bindTo { it.config }
>     val configMap = myConfigMap("config_map").bindTo { it.configMap }
> }
> ```
> 
> 在dao 里可以直接使用
> 
> ```
>     fun getConfById(id: Long): TestEntity? {
>         val testConf = db.sequenceOf(TestEntitys).find { it.id eq id }
>         val config =  testConf?.config
>         val configMap = testConf?.configMap
>         return testConf
>     }
> ```
好的，我试试，多谢多谢🙏🙏🙏

**Comment by ParadiseHell** [comment]
@onXoot 好的，我试试，多谢多谢🙏🙏🙏

**Comment by ParadiseHell** [comment]
@onXoot 试过了，非常好用，感谢🙏🙏🙏
