### ISSUE TITLE
Generic caching interface

### ISSUE THREAD

**Issue by JoonasC** [kotlin-orm/ktorm#54]
It would be nice if Ktorm offered a generic caching interface, so users could implement their own caching systems for db queries using eg. Redis or Ehcache.

The interface could look something like this:
```
interface KtormCache {
  fun getFromCache(generatedSql: String): QueryRowSet?
}
```

And a sample implementation:
```
class KtormCacheRedisImpl : KtormCache {
  override fun getFromCache(generatedSql: String): QueryRowSet? {
    // Return query results from redis by the generated sql, or null if not found
  }
}
```

Thanks.

**Comment by vincentlauvlwj** [comment]
Thank you for your suggestion. 

But I don't think an ORM framework should support caching. My design philosophy is to do one thing and do it well. The caching can be implemented with other tools. 

In addition, implementing caching is not so simple. We have to consider the expiring of the cached elements and the invalidation strategies, which will greatly increase the complexity of Ktorm. I want to keep Ktorm simple. 

So, let's postpone that issue until anyone else asks for that.

**Comment by JoonasC** [comment]
Ok, thanks for your reply.
Could you give me an example of what you mean by other tools?

Also, you could leave the implementation of the invalidation strategy/cached element expiration to the users (even though it would of course be nicer if Ktorm had it out of the box), after all it is the user's code that will either return a null query row set or not.
So the implementation could just return null when a cached element has expired in addition to situations where such a cached element has not been found.

**Comment by vincentlauvlwj** [comment]
Google Guava is a great library that provides an effective caching implementation. Here is an example: 

```kotlin
class DepartmentService {
    private val cache = CacheBuilder.newBuilder()
        .expireAfterWrite(1, TimeUnit.MINUTES)
        .build<Int, Department>()

    fun getDepartmentById(id: Int): Department? {
        return cache.get(id) { Departments.findById(id) }
    }

    fun addDepartment(name: String, location: String) {
        val department = Department()
        department.name = name
        department.location = location
        Departments.add(department)
        cache.put(department.id, department)
    }

    fun updateInfo(id: Int, name: String, location: String) {
        val department = Departments.findById(id) ?: return
        department.name = name
        department.location = location
        department.flushChanges()
        cache.put(id, department)
    }

    fun deleteDepartment(id: Int) {
        Departments.delete { it.id eq id }
        cache.invalidate(id)
    }
}
```

There are also some other caching libraries, like Spring Cache, JetCache and so on. They are very mature and have superior performance. We should choose one of them instead of implementing caching in an ORM framework.

**Comment by JoonasC** [comment]
Ok, feel free to close this if you want to.
