### ISSUE TITLE
自定义支持MySQL的find_in_set函数

### ISSUE THREAD

**Issue by weifengze** [kotlin-orm/ktorm#541]
怎么自定义支持MySQL的find_in_set函数？

**Comment by auhouhs** [comment]
![image](https://github.com/kotlin-orm/ktorm/assets/17831176/311d4e88-7626-4955-88e9-5a5588e8bb34)
写的马马虎虎，不确定有没有可以复用的类，也不确定有没有什么隐藏的问题，不过效果可以实现，你参考下呢

**Comment by weifengze** [comment]
谢谢呢~

**Comment by vincentlauvlwj** [comment]
@auhouhs 没必要单独定义一个表达式类，可以直接用 `FunctionExpression`，写起来更简单

**Comment by auhouhs** [comment]
@vincentlauvlwj 我仔细看了一下，用`FunctionExpression`确实会更简单
![image](https://github.com/kotlin-orm/ktorm/assets/17831176/83eab039-d32e-4d80-a406-9ef28da487b0)
我修改了一下，你再参考一下呢，这个简单很多，不用单独定义表达式类了 @weifengze

**Comment by weifengze** [comment]
@auhouhs 谢谢大佬的代码，我一会儿试一下！
@vincentlauvlwj 谢谢大佬开发的ORM框架！
