### ISSUE TITLE
Ktorm 别名机制似乎有问题

### ISSUE THREAD

**Issue by rhz-b** [kotlin-orm/ktorm#555]
作者，您好！

按照Ktorm文档的指导，我可以正常执行这个查询（说明 Employees.departmentId 是存在的且能映射到表的字段）：
val query = database
    .from(Employees)
    .select(Employees.name)
    .whereWithConditions {
        if (someCondition) {
            it += Employees.managerId.isNull()
        }
        if (otherCondition) {
            it += Employees.departmentId eq 1
        }
    }
	
但不能执行以下查询：
val t = Employees.aliased("t")
database
    .from(t)
    .select(t.departmentId, avg(t.salary))
    .groupBy(t.departmentId)
    .having { avg(t.salary) gt 100.0 }
    .forEach { row -> 
        println("${row.getInt(1)}:${row.getDouble(2)}")
    }
	
IDEA 提示没有 t.departmentId，但如前所示 Employees.departmentId 是有的，不知是何原因？

**Comment by vincentlauvlwj** [comment]
别名机制对表对象的定义有特殊要求，需要写点特殊的代码，参考官网文档：[自连接查询与表别名](https://www.ktorm.org/zh-cn/joining.html#%E8%87%AA%E8%BF%9E%E6%8E%A5%E6%9F%A5%E8%AF%A2%E4%B8%8E%E8%A1%A8%E5%88%AB%E5%90%8D)

当然，这些代码在 4.0 版本也可以实现自动生成，参考 https://github.com/kotlin-orm/ktorm/releases/tag/v4.0.0

**Comment by rhz-b** [comment]
vincentlauvlwj，您好！

    按您的方法问题解决了，非常感谢！
