### ISSUE TITLE
使用实体查询,框架会拼接字段名称为【表别名_字段】而遭到 ColumnNameChecker 字段名称过长拦截

### ISSUE THREAD

**Issue by canmengqian** [kotlin-orm/ktorm#566]
通过元数据里的**maxColumnNameLength** 和拼接后的字段 来进行比较长度,导致因为拼接了表别名的原因遭到ColumnNameChecker 拦截

![image](https://github.com/kotlin-orm/ktorm/assets/24270554/56c917f4-20f8-4983-91d2-fc9eb7f79340)

![image](https://github.com/kotlin-orm/ktorm/assets/24270554/844562e5-8b4b-43e9-9136-9688531d1afc)

![image](https://github.com/kotlin-orm/ktorm/assets/24270554/e90d4e58-6969-4fb3-8b82-e6dbbc45ae97)

**Comment by vincentlauvlwj** [comment]
alias 短一点，单字母就可以，30 个字符的长度够用了

**Comment by canmengqian** [comment]
@vincentlauvlwj 目前项目里有些列名已经接近30个字符，拼上表别名就超了 😂😂😂

**Comment by vincentlauvlwj** [comment]
@canmengqian 你用的是什么数据库，一般数据库的长度限制都是 64 左右，30 比较少见

**Comment by vincentlauvlwj** [comment]
> @vincentlauvlwj 目前项目里有些列名已经接近30个字符，拼上表别名就超了 😂😂😂

那也没办法，只能精简一下字段名，这里不校验的话，有些数据库会把超出长度的名字截断，会导致更隐蔽的 bug

**Comment by canmengqian** [comment]
@vincentlauvlwj  用的Oracle数据库,是不是可以考虑不用将表别名纳入校验范围内,或者可以提供卸载拦截器的方式，或加上自定义拦截器接口
