### ISSUE TITLE
4.0+版本使用KSP生成实体类不兼容无符号整数类型

### ISSUE THREAD

**Issue by SamiuZhong** [kotlin-orm/ktorm#574]
我注意到 #253 在老版本似乎是兼容无符号整数类型的，但是现在4.0+版本我使用KSP自动生成实体类，当将字段设置为无符号整数如 `UInt` 或 `ULong` 等类型时编译会出错。
请问是我的打开方式不对吗？还是等以后版本做兼容呢？

**Comment by vincentlauvlwj** [comment]
错误信息发一下

**Comment by SamiuZhong** [comment]
@vincentlauvlwj 
![image](https://github.com/user-attachments/assets/fdc78893-7188-4ac1-aab7-9fc4d9b8d382)

**Comment by vincentlauvlwj** [comment]
之前的支持只是允许我们在实体类中使用内联类型而不出现兼容性问题而已，并不意味着 ktorm 内置了无符号整数的 `SqlType`

这个错误提示已经很直白了，`ULong` 不是 ktorm 内置的类型，需要手动指定一个定制的 `SqlType` 实现类

```kotlin
@Table
interface Employee: Entity<Employee> {
    @PrimaryKey
    @Column(sqlType = ULongSqlType::class)
    var id: ULong
    var name: String
    var nickname: String
}

object ULongSqlType : SqlType<ULong>(Types.BIGINT, "bigint unsigned") {
    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: ULong) {
        ps.setLong(index, parameter.toLong())
    }

    override fun doGetResult(rs: ResultSet, index: Int): ULong {
        return rs.getLong(index).toULong()
    }
}
```

**Comment by SamiuZhong** [comment]
@vincentlauvlwj 您好，我注意到 `ULongSqlType` 的拓展类是通过 `Long.toULong()` 方法和 `ULong.toLong()` 方法来进行类型的转换、存储和读取的，那么这里的数据长度理论上也会受到 `Long` 类型数据长度的限制。

经过测试，实际情况也验证了我的想法。即这里的数据长度最大只能为 `Long.MAX_VALUE(2^63 - 1)` 而并不是 `ULong.MAX_VALUE(2^64 - 1)` ，当我尝试插入数据 `2^64` 时，系统会报长度溢出错误，报错信息如下图。

`UInt` 类型同理也有一样的问题。

如果无符号类型的长度也要受到有符号类型长度的限制，那感觉这里的 `ULong` `UInt` 等无符号类型就完全没有存在的意义了呀，都可以使用有符号类型来替代。

请问这个问题应该如何解决呢？还是说目前看来就是个无解的问题？

![1723099119517](https://github.com/user-attachments/assets/013e7c6e-3728-4f1d-a6b0-2924908171f1)

**Comment by vincentlauvlwj** [comment]
上面那个 `ULongSqlType` 只是随手写的一个示例，不要当真

要避免溢出的问题，我们在使用 JDBC 与 MySQL 交互的时候，`ULong` 就不能转换成 `Long`，而应该转换成 `BigInteger`，可以参考这段代码：

```kotlin
object ULongSqlType : SqlType<ULong>(Types.BIGINT, "bigint unsigned") {

    override fun doSetParameter(ps: PreparedStatement, index: Int, parameter: ULong) {
        val bytes = ByteArray(8)
        bytes[0] = (parameter shr 56).toByte()
        bytes[1] = (parameter shr 48).toByte()
        bytes[2] = (parameter shr 40).toByte()
        bytes[3] = (parameter shr 32).toByte()
        bytes[4] = (parameter shr 24).toByte()
        bytes[5] = (parameter shr 16).toByte()
        bytes[6] = (parameter shr 8).toByte()
        bytes[7] = parameter.toByte()
        ps.setObject(index, BigInteger(1, bytes))
    }

    override fun doGetResult(rs: ResultSet, index: Int): ULong? {
        val value = rs.getObject(index) as BigInteger?
        return value?.toLong()?.toULong()
    }
}
```
