### ISSUE TITLE
Locking a row using FOR UPDATE

### ISSUE THREAD

**Issue by ashokgelal** [kotlin-orm/ktorm#69]
What would be a good way to lock a row when performing a SELECT? https://stackoverflow.com/questions/6066205/when-using-mysqls-for-update-locking-what-is-exactly-locked

I couldn't find anything that's even close. If there isn't anything built-in, could this be done easily using an extension?

**Comment by vincentlauvlwj** [comment]
We have [SqlExpression.extraProperties](https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-core/src/main/kotlin/me/liuwj/ktorm/expression/SqlExpressions.kt#L51), that can help us to custom the SQL DSL. 

Write an extension function for `Query` to set a flag into `extraProperties`: 

```kotlin
fun Query.forUpdate(): Query {
    val expr = this.expression

    val exprForUpdate = when (expr) {
        is SelectExpression -> expr.copy(extraProperties = expr.extraProperties + Pair("forUpdate", true))
        is UnionExpression -> expr.copy(extraProperties = expr.extraProperties + Pair("forUpdate", true))
    }

    return this.copy(expression = exprForUpdate)
}
```

Write a custom SQL formatter to read the flag and generate the correct SQL: 

```kotlin
class CustomSqlFormatter(database: Database, beautifySql: Boolean, indentSize: Int)
    : MySqlFormatter(database, beautifySql, indentSize) {

    override fun visitQuery(expr: QueryExpression): QueryExpression {
        super.visitQuery(expr)

        if ("forUpdate" in expr.extraProperties) {
            write("for update ");
        }

        return expr
    }
}
```

Connect to database with our custom SQL formatter: 

```kotlin
Database.connect(
    url = "jdbc:mysql://localhost:3306/ktorm",
    driver = "com.mysql.jdbc.Driver",
    dialect = object : SqlDialect {
        override fun createSqlFormatter(database: Database, beautifySql: Boolean, indentSize: Int): SqlFormatter {
            return CustomSqlFormatter(database, beautifySql, indentSize)
        }
    }
)
```

Then we can use it: 

```kotlin
val query = Employees
    .select(Employees.id, Employees.name)
    .where { Employees.id eq 1 }
    .forUpdate()
```

Generated SQL: 

```mysql
select t_employee.id as t_employee_id, t_employee.name as t_employee_name 
from t_employee 
where t_employee.id = ? 
for update
```

**Comment by ashokgelal** [comment]
You are the best! Thank you!!

Any thoughts about adding this to supported core dialects?

**Comment by vincentlauvlwj** [comment]
Will add to MySQL dialect.

**Comment by ragnese** [comment]
Would it be okay to leave this issue open until it's actually implemented? It doesn't seem to exist in the MySQL dialect yet.

**Comment by vincentlauvlwj** [comment]
@ragnese Sure. 

Sorry that I almost forgot this issue.

**Comment by vincentlauvlwj** [comment]
Supported in Ktorm 3.1.0.
