### ISSUE TITLE
Unable to use PostgreSQL Namespaces

### ISSUE THREAD

**Issue by mdimond** [kotlin-orm/ktorm#89]
While implementing Ktorm we have run across an issue where we are unable to specify the namespace of a table. Example below

order.orders with order being the namespace and orders the table.  This would mean we would need the ability to specify the namespace in the ORM.

If we create the table within postgreSQL public namespace everything works fine.

Is there support for specifying a namespace?

Is there anyone out there successfully using Ktorm with namespaces?

**Comment by vincentlauvlwj** [comment]
This is not supported yet. We will support it in the future. 

As a workaround now, you can specify the schema on the connection URL, which works fine: 

```kotlin
val database = Database.connect("jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema")
```

See https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc

**Comment by antonydenyer** [comment]
What are you currently thinking? Add schema name in the table class?

**Comment by vincentlauvlwj** [comment]
@antonydenyer Yes, will add schema name in the table class.

**Comment by vincentlauvlwj** [comment]
Supported in Ktorm 3.1.0.
